# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
SPDX-License-Identifier: BSD-3-Clause
---------------------------------------------------------------------
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _Precision:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PrecisionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Precision.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PRECISION_UNSPECIFIED: _Precision.ValueType  # 0
    PRECISION_FLOAT: _Precision.ValueType  # 1
    """No quantization (floating point)"""
    PRECISION_W8A8: _Precision.ValueType  # 2
    """8-bit weights, 8-bit activations"""
    PRECISION_W8A16: _Precision.ValueType  # 3
    """8-bit weights, 16-bit activations"""
    PRECISION_W16A16: _Precision.ValueType  # 4
    """16-bit weights, 16-bit activations"""
    PRECISION_W4A16: _Precision.ValueType  # 5
    """4-bit weights, 16-bit activations"""
    PRECISION_W4: _Precision.ValueType  # 6
    """4-bit weights only"""
    PRECISION_W8A8_MIXED_INT16: _Precision.ValueType  # 7
    """8-bit w/a with 16-bit int override"""
    PRECISION_W8A16_MIXED_INT16: _Precision.ValueType  # 8
    """8-bit w, 16-bit a with 16-bit int override"""
    PRECISION_W8A8_MIXED_FP16: _Precision.ValueType  # 9
    """8-bit w/a with FP16 override"""
    PRECISION_W8A16_MIXED_FP16: _Precision.ValueType  # 10
    """8-bit w, 16-bit a with FP16 override"""
    PRECISION_MXFP4: _Precision.ValueType  # 11
    """GGUF format (llama.cpp)"""
    PRECISION_Q8_0: _Precision.ValueType  # 12
    """GGUF format (llama.cpp)"""
    PRECISION_Q4_0: _Precision.ValueType  # 13
    """GGUF format (llama.cpp)"""
    PRECISION_MIXED: _Precision.ValueType  # 14
    """Component with multiple precisions, no float layers"""
    PRECISION_MIXED_WITH_FLOAT: _Precision.ValueType  # 15
    """Component with multiple precisions, at least one float layer"""

class Precision(_Precision, metaclass=_PrecisionEnumTypeWrapper): ...

PRECISION_UNSPECIFIED: Precision.ValueType  # 0
PRECISION_FLOAT: Precision.ValueType  # 1
"""No quantization (floating point)"""
PRECISION_W8A8: Precision.ValueType  # 2
"""8-bit weights, 8-bit activations"""
PRECISION_W8A16: Precision.ValueType  # 3
"""8-bit weights, 16-bit activations"""
PRECISION_W16A16: Precision.ValueType  # 4
"""16-bit weights, 16-bit activations"""
PRECISION_W4A16: Precision.ValueType  # 5
"""4-bit weights, 16-bit activations"""
PRECISION_W4: Precision.ValueType  # 6
"""4-bit weights only"""
PRECISION_W8A8_MIXED_INT16: Precision.ValueType  # 7
"""8-bit w/a with 16-bit int override"""
PRECISION_W8A16_MIXED_INT16: Precision.ValueType  # 8
"""8-bit w, 16-bit a with 16-bit int override"""
PRECISION_W8A8_MIXED_FP16: Precision.ValueType  # 9
"""8-bit w/a with FP16 override"""
PRECISION_W8A16_MIXED_FP16: Precision.ValueType  # 10
"""8-bit w, 16-bit a with FP16 override"""
PRECISION_MXFP4: Precision.ValueType  # 11
"""GGUF format (llama.cpp)"""
PRECISION_Q8_0: Precision.ValueType  # 12
"""GGUF format (llama.cpp)"""
PRECISION_Q4_0: Precision.ValueType  # 13
"""GGUF format (llama.cpp)"""
PRECISION_MIXED: Precision.ValueType  # 14
"""Component with multiple precisions, no float layers"""
PRECISION_MIXED_WITH_FLOAT: Precision.ValueType  # 15
"""Component with multiple precisions, at least one float layer"""
global___Precision = Precision
