# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/precision.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16shared/precision.proto\x12\x05qaihm*\x93\x03\n\tPrecision\x12\x19\n\x15PRECISION_UNSPECIFIED\x10\x00\x12\x13\n\x0fPRECISION_FLOAT\x10\x01\x12\x12\n\x0ePRECISION_W8A8\x10\x02\x12\x13\n\x0fPRECISION_W8A16\x10\x03\x12\x14\n\x10PRECISION_W16A16\x10\x04\x12\x13\n\x0fPRECISION_W4A16\x10\x05\x12\x10\n\x0cPRECISION_W4\x10\x06\x12\x1e\n\x1aPRECISION_W8A8_MIXED_INT16\x10\x07\x12\x1f\n\x1bPRECISION_W8A16_MIXED_INT16\x10\x08\x12\x1d\n\x19PRECISION_W8A8_MIXED_FP16\x10\t\x12\x1e\n\x1aPRECISION_W8A16_MIXED_FP16\x10\n\x12\x13\n\x0fPRECISION_MXFP4\x10\x0b\x12\x12\n\x0ePRECISION_Q8_0\x10\x0c\x12\x12\n\x0ePRECISION_Q4_0\x10\r\x12\x13\n\x0fPRECISION_MIXED\x10\x0e\x12\x1e\n\x1aPRECISION_MIXED_WITH_FLOAT\x10\x0f\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shared.precision_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRECISION']._serialized_start=34
  _globals['_PRECISION']._serialized_end=437
# @@protoc_insertion_point(module_scope)
