# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/range.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12shared/range.proto\x12\x05qaihm\">\n\x08IntRange\x12\x10\n\x03min\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x10\n\x03max\x18\x02 \x01(\x03H\x01\x88\x01\x01\x42\x06\n\x04_minB\x06\n\x04_max\"A\n\x0b\x44oubleRange\x12\x10\n\x03min\x18\x01 \x01(\x01H\x00\x88\x01\x01\x12\x10\n\x03max\x18\x02 \x01(\x01H\x01\x88\x01\x01\x42\x06\n\x04_minB\x06\n\x04_max\"Y\n\x05Range\x12 \n\x05int_r\x18\x01 \x01(\x0b\x32\x0f.qaihm.IntRangeH\x00\x12&\n\x08\x64ouble_r\x18\x02 \x01(\x0b\x32\x12.qaihm.DoubleRangeH\x00\x42\x06\n\x04typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shared.range_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INTRANGE']._serialized_start=29
  _globals['_INTRANGE']._serialized_end=91
  _globals['_DOUBLERANGE']._serialized_start=93
  _globals['_DOUBLERANGE']._serialized_end=158
  _globals['_RANGE']._serialized_start=160
  _globals['_RANGE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
