# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
SPDX-License-Identifier: BSD-3-Clause
---------------------------------------------------------------------

Tensor specification types for model I/O.

Defines the core types for specifying tensor metadata:
- TensorSpec: Specification for a tensor (shape, dtype, metadata)
- IoType: Semantic type of a tensor (image, tensor, bbox)
- ColorFormat: Color format for image tensors
- ImageMetadata: Metadata for image tensors
- BboxFormat: Bounding box coordinate format
- BboxMetadata: Metadata for bounding box tensors

These types are used in model.get_input_spec() and in metadata.yaml files.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import shared.range_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _DType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DTYPE_UNSPECIFIED: _DType.ValueType  # 0
    DTYPE_FLOAT16: _DType.ValueType  # 1
    DTYPE_FLOAT32: _DType.ValueType  # 2
    DTYPE_FLOAT64: _DType.ValueType  # 3
    DTYPE_INT8: _DType.ValueType  # 4
    DTYPE_INT16: _DType.ValueType  # 5
    DTYPE_INT32: _DType.ValueType  # 6
    DTYPE_INT64: _DType.ValueType  # 7
    DTYPE_UINT8: _DType.ValueType  # 8
    DTYPE_UINT16: _DType.ValueType  # 9
    DTYPE_UINT32: _DType.ValueType  # 10
    DTYPE_UINT64: _DType.ValueType  # 11
    DTYPE_BOOL: _DType.ValueType  # 12

class DType(_DType, metaclass=_DTypeEnumTypeWrapper): ...

DTYPE_UNSPECIFIED: DType.ValueType  # 0
DTYPE_FLOAT16: DType.ValueType  # 1
DTYPE_FLOAT32: DType.ValueType  # 2
DTYPE_FLOAT64: DType.ValueType  # 3
DTYPE_INT8: DType.ValueType  # 4
DTYPE_INT16: DType.ValueType  # 5
DTYPE_INT32: DType.ValueType  # 6
DTYPE_INT64: DType.ValueType  # 7
DTYPE_UINT8: DType.ValueType  # 8
DTYPE_UINT16: DType.ValueType  # 9
DTYPE_UINT32: DType.ValueType  # 10
DTYPE_UINT64: DType.ValueType  # 11
DTYPE_BOOL: DType.ValueType  # 12
global___DType = DType

class _IoType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _IoTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_IoType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    IO_TYPE_UNSPECIFIED: _IoType.ValueType  # 0
    IO_TYPE_TENSOR: _IoType.ValueType  # 1
    IO_TYPE_IMAGE: _IoType.ValueType  # 2
    IO_TYPE_BBOX: _IoType.ValueType  # 3

class IoType(_IoType, metaclass=_IoTypeEnumTypeWrapper):
    """Semantic type of an input/output tensor."""

IO_TYPE_UNSPECIFIED: IoType.ValueType  # 0
IO_TYPE_TENSOR: IoType.ValueType  # 1
IO_TYPE_IMAGE: IoType.ValueType  # 2
IO_TYPE_BBOX: IoType.ValueType  # 3
global___IoType = IoType

class _ColorFormat:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ColorFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ColorFormat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    COLOR_FORMAT_UNSPECIFIED: _ColorFormat.ValueType  # 0
    COLOR_FORMAT_RGB: _ColorFormat.ValueType  # 1
    COLOR_FORMAT_BGR: _ColorFormat.ValueType  # 2
    COLOR_FORMAT_GRAYSCALE: _ColorFormat.ValueType  # 3

class ColorFormat(_ColorFormat, metaclass=_ColorFormatEnumTypeWrapper):
    """Color channel format for image tensors."""

COLOR_FORMAT_UNSPECIFIED: ColorFormat.ValueType  # 0
COLOR_FORMAT_RGB: ColorFormat.ValueType  # 1
COLOR_FORMAT_BGR: ColorFormat.ValueType  # 2
COLOR_FORMAT_GRAYSCALE: ColorFormat.ValueType  # 3
global___ColorFormat = ColorFormat

class _BboxFormat:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _BboxFormatEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BboxFormat.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    BBOX_FORMAT_UNSPECIFIED: _BboxFormat.ValueType  # 0
    BBOX_FORMAT_XYXY: _BboxFormat.ValueType  # 1
    """(x1, y1, x2, y2) - top-left and bottom-right corners"""
    BBOX_FORMAT_XYWH: _BboxFormat.ValueType  # 2
    """(x, y, width, height) - top-left corner and size"""
    BBOX_FORMAT_CXCYWH: _BboxFormat.ValueType  # 3
    """(cx, cy, width, height) - center and size"""

class BboxFormat(_BboxFormat, metaclass=_BboxFormatEnumTypeWrapper):
    """Bounding box coordinate format."""

BBOX_FORMAT_UNSPECIFIED: BboxFormat.ValueType  # 0
BBOX_FORMAT_XYXY: BboxFormat.ValueType  # 1
"""(x1, y1, x2, y2) - top-left and bottom-right corners"""
BBOX_FORMAT_XYWH: BboxFormat.ValueType  # 2
"""(x, y, width, height) - top-left corner and size"""
BBOX_FORMAT_CXCYWH: BboxFormat.ValueType  # 3
"""(cx, cy, width, height) - center and size"""
global___BboxFormat = BboxFormat

@typing.final
class ImageMetadata(google.protobuf.message.Message):
    """Metadata specific to image tensor inputs.
    Groups image-related metadata fields like color format and value range.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLOR_FORMAT_FIELD_NUMBER: builtins.int
    color_format: global___ColorFormat.ValueType
    def __init__(
        self,
        *,
        color_format: global___ColorFormat.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["color_format", b"color_format"]) -> None: ...

global___ImageMetadata = ImageMetadata

@typing.final
class BboxMetadata(google.protobuf.message.Message):
    """Metadata specific to bounding box tensor outputs.
    Groups bbox-related metadata fields like coordinate format.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BBOX_FORMAT_FIELD_NUMBER: builtins.int
    bbox_format: global___BboxFormat.ValueType
    def __init__(
        self,
        *,
        bbox_format: global___BboxFormat.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["bbox_format", b"bbox_format"]) -> None: ...

global___BboxMetadata = BboxMetadata

@typing.final
class QuantizationParameters(google.protobuf.message.Message):
    """Quantization parameters for a tensor."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SCALE_FIELD_NUMBER: builtins.int
    ZERO_POINT_FIELD_NUMBER: builtins.int
    scale: builtins.float
    zero_point: builtins.int
    def __init__(
        self,
        *,
        scale: builtins.float = ...,
        zero_point: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["scale", b"scale", "zero_point", b"zero_point"]) -> None: ...

global___QuantizationParameters = QuantizationParameters

@typing.final
class TensorSpec(google.protobuf.message.Message):
    """Specification for an input or output tensor."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    DTYPE_FIELD_NUMBER: builtins.int
    QUANTIZATION_PARAMETERS_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    VALUE_RANGE_FIELD_NUMBER: builtins.int
    IO_TYPE_FIELD_NUMBER: builtins.int
    IMAGE_METADATA_FIELD_NUMBER: builtins.int
    BBOX_METADATA_FIELD_NUMBER: builtins.int
    SOFTMAX_APPLIED_FIELD_NUMBER: builtins.int
    LABELS_FILE_FIELD_NUMBER: builtins.int
    name: builtins.str
    """Generic Tensor Metadata"""
    dtype: global___DType.ValueType
    description: builtins.str
    io_type: global___IoType.ValueType
    """IMAGE for image tensors, TENSOR for generic tensors."""
    softmax_applied: builtins.bool
    """Whether softmax/sigmoid has been applied to this tensor's values."""
    labels_file: builtins.str
    """Name of the labels file that maps indices to class names
    (e.g. "coco_labels.txt").
    """
    @property
    def shape(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def quantization_parameters(self) -> global___QuantizationParameters: ...
    @property
    def value_range(self) -> shared.range_pb2.Range:
        """Tensor value range."""

    @property
    def image_metadata(self) -> global___ImageMetadata:
        """Image-specific metadata (color_format). Only used when io_type is IMAGE."""

    @property
    def bbox_metadata(self) -> global___BboxMetadata:
        """Bbox-specific metadata (bbox_format). Only used when io_type is BBOX."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        shape: collections.abc.Iterable[builtins.int] | None = ...,
        dtype: global___DType.ValueType = ...,
        quantization_parameters: global___QuantizationParameters | None = ...,
        description: builtins.str | None = ...,
        value_range: shared.range_pb2.Range | None = ...,
        io_type: global___IoType.ValueType = ...,
        image_metadata: global___ImageMetadata | None = ...,
        bbox_metadata: global___BboxMetadata | None = ...,
        softmax_applied: builtins.bool = ...,
        labels_file: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_bbox_metadata", b"_bbox_metadata", "_description", b"_description", "_image_metadata", b"_image_metadata", "_labels_file", b"_labels_file", "_quantization_parameters", b"_quantization_parameters", "_value_range", b"_value_range", "bbox_metadata", b"bbox_metadata", "description", b"description", "image_metadata", b"image_metadata", "labels_file", b"labels_file", "quantization_parameters", b"quantization_parameters", "value_range", b"value_range"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_bbox_metadata", b"_bbox_metadata", "_description", b"_description", "_image_metadata", b"_image_metadata", "_labels_file", b"_labels_file", "_quantization_parameters", b"_quantization_parameters", "_value_range", b"_value_range", "bbox_metadata", b"bbox_metadata", "description", b"description", "dtype", b"dtype", "image_metadata", b"image_metadata", "io_type", b"io_type", "labels_file", b"labels_file", "name", b"name", "quantization_parameters", b"quantization_parameters", "shape", b"shape", "softmax_applied", b"softmax_applied", "value_range", b"value_range"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_bbox_metadata", b"_bbox_metadata"]) -> typing.Literal["bbox_metadata"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_description", b"_description"]) -> typing.Literal["description"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_image_metadata", b"_image_metadata"]) -> typing.Literal["image_metadata"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_labels_file", b"_labels_file"]) -> typing.Literal["labels_file"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_quantization_parameters", b"_quantization_parameters"]) -> typing.Literal["quantization_parameters"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_value_range", b"_value_range"]) -> typing.Literal["value_range"] | None: ...

global___TensorSpec = TensorSpec
