# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared/tensor_spec.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qai_hub_models_cli.proto.shared import range_pb2 as shared_dot_range__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18shared/tensor_spec.proto\x12\x05qaihm\x1a\x12shared/range.proto\"9\n\rImageMetadata\x12(\n\x0c\x63olor_format\x18\x01 \x01(\x0e\x32\x12.qaihm.ColorFormat\";\n\x16QuantizationParameters\x12\r\n\x05scale\x18\x01 \x01(\x01\x12\x12\n\nzero_point\x18\x02 \x01(\x05\"\xef\x02\n\nTensorSpec\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x05\x12\x1b\n\x05\x64type\x18\x03 \x01(\x0e\x32\x0c.qaihm.DType\x12\x43\n\x17quantization_parameters\x18\x04 \x01(\x0b\x32\x1d.qaihm.QuantizationParametersH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x05 \x01(\tH\x01\x88\x01\x01\x12&\n\x0bvalue_range\x18\x06 \x01(\x0b\x32\x0c.qaihm.RangeH\x02\x88\x01\x01\x12\x1e\n\x07io_type\x18\x07 \x01(\x0e\x32\r.qaihm.IoType\x12\x31\n\x0eimage_metadata\x18\x08 \x01(\x0b\x32\x14.qaihm.ImageMetadataH\x03\x88\x01\x01\x42\x1a\n\x18_quantization_parametersB\x0e\n\x0c_descriptionB\x0e\n\x0c_value_rangeB\x11\n\x0f_image_metadata*\xf1\x01\n\x05\x44Type\x12\x15\n\x11\x44TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rDTYPE_FLOAT16\x10\x01\x12\x11\n\rDTYPE_FLOAT32\x10\x02\x12\x11\n\rDTYPE_FLOAT64\x10\x03\x12\x0e\n\nDTYPE_INT8\x10\x04\x12\x0f\n\x0b\x44TYPE_INT16\x10\x05\x12\x0f\n\x0b\x44TYPE_INT32\x10\x06\x12\x0f\n\x0b\x44TYPE_INT64\x10\x07\x12\x0f\n\x0b\x44TYPE_UINT8\x10\x08\x12\x10\n\x0c\x44TYPE_UINT16\x10\t\x12\x10\n\x0c\x44TYPE_UINT32\x10\n\x12\x10\n\x0c\x44TYPE_UINT64\x10\x0b\x12\x0e\n\nDTYPE_BOOL\x10\x0c*Z\n\x06IoType\x12\x17\n\x13IO_TYPE_UNSPECIFIED\x10\x00\x12\x12\n\x0eIO_TYPE_TENSOR\x10\x01\x12\x11\n\rIO_TYPE_IMAGE\x10\x02\x12\x10\n\x0cIO_TYPE_BBOX\x10\x03*s\n\x0b\x43olorFormat\x12\x1c\n\x18\x43OLOR_FORMAT_UNSPECIFIED\x10\x00\x12\x14\n\x10\x43OLOR_FORMAT_RGB\x10\x01\x12\x14\n\x10\x43OLOR_FORMAT_BGR\x10\x02\x12\x1a\n\x16\x43OLOR_FORMAT_GRAYSCALE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shared.tensor_spec_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DTYPE']._serialized_start=546
  _globals['_DTYPE']._serialized_end=787
  _globals['_IOTYPE']._serialized_start=789
  _globals['_IOTYPE']._serialized_end=879
  _globals['_COLORFORMAT']._serialized_start=881
  _globals['_COLORFORMAT']._serialized_end=996
  _globals['_IMAGEMETADATA']._serialized_start=55
  _globals['_IMAGEMETADATA']._serialized_end=112
  _globals['_QUANTIZATIONPARAMETERS']._serialized_start=114
  _globals['_QUANTIZATIONPARAMETERS']._serialized_end=173
  _globals['_TENSORSPEC']._serialized_start=176
  _globals['_TENSORSPEC']._serialized_end=543
# @@protoc_insertion_point(module_scope)
