# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
SPDX-License-Identifier: BSD-3-Clause
---------------------------------------------------------------------
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ToolVersions(google.protobuf.message.Message):
    """Toolchains used to compile or profile models."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AI_HUB_MODELS_FIELD_NUMBER: builtins.int
    QAIRT_FIELD_NUMBER: builtins.int
    ONNX_FIELD_NUMBER: builtins.int
    ONNX_RUNTIME_FIELD_NUMBER: builtins.int
    TFLITE_FIELD_NUMBER: builtins.int
    LITERT_FIELD_NUMBER: builtins.int
    ai_hub_models: builtins.str
    qairt: builtins.str
    onnx: builtins.str
    onnx_runtime: builtins.str
    tflite: builtins.str
    litert: builtins.str
    def __init__(
        self,
        *,
        ai_hub_models: builtins.str | None = ...,
        qairt: builtins.str | None = ...,
        onnx: builtins.str | None = ...,
        onnx_runtime: builtins.str | None = ...,
        tflite: builtins.str | None = ...,
        litert: builtins.str | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_ai_hub_models", b"_ai_hub_models", "_litert", b"_litert", "_onnx", b"_onnx", "_onnx_runtime", b"_onnx_runtime", "_qairt", b"_qairt", "_tflite", b"_tflite", "ai_hub_models", b"ai_hub_models", "litert", b"litert", "onnx", b"onnx", "onnx_runtime", b"onnx_runtime", "qairt", b"qairt", "tflite", b"tflite"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_ai_hub_models", b"_ai_hub_models", "_litert", b"_litert", "_onnx", b"_onnx", "_onnx_runtime", b"_onnx_runtime", "_qairt", b"_qairt", "_tflite", b"_tflite", "ai_hub_models", b"ai_hub_models", "litert", b"litert", "onnx", b"onnx", "onnx_runtime", b"onnx_runtime", "qairt", b"qairt", "tflite", b"tflite"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_ai_hub_models", b"_ai_hub_models"]) -> typing.Literal["ai_hub_models"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_litert", b"_litert"]) -> typing.Literal["litert"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_onnx", b"_onnx"]) -> typing.Literal["onnx"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_onnx_runtime", b"_onnx_runtime"]) -> typing.Literal["onnx_runtime"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_qairt", b"_qairt"]) -> typing.Literal["qairt"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_tflite", b"_tflite"]) -> typing.Literal["tflite"] | None: ...

global___ToolVersions = ToolVersions
