# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
SPDX-License-Identifier: BSD-3-Clause
---------------------------------------------------------------------
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
from qai_hub_models_cli.proto import numerics_pb2
from qai_hub_models_cli.proto import platform_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ModelLicense:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ModelLicenseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ModelLicense.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MODEL_LICENSE_UNSPECIFIED: _ModelLicense.ValueType  # 0
    MODEL_LICENSE_UNLICENSED: _ModelLicense.ValueType  # 1
    """General"""
    MODEL_LICENSE_COMMERCIAL: _ModelLicense.ValueType  # 2
    MODEL_LICENSE_AI_HUB_MODELS_LICENSE: _ModelLicense.ValueType  # 3
    MODEL_LICENSE_APACHE_2_0: _ModelLicense.ValueType  # 4
    """Non-restrictive"""
    MODEL_LICENSE_MIT: _ModelLicense.ValueType  # 5
    MODEL_LICENSE_BSD_3_CLAUSE: _ModelLicense.ValueType  # 6
    MODEL_LICENSE_CC_BY_4_0: _ModelLicense.ValueType  # 7
    MODEL_LICENSE_AGPL_3_0: _ModelLicense.ValueType  # 8
    """Copyleft (derivative works must have the same license)"""
    MODEL_LICENSE_GPL_3_0: _ModelLicense.ValueType  # 9
    MODEL_LICENSE_CREATIVEML_OPENRAIL_M: _ModelLicense.ValueType  # 10
    MODEL_LICENSE_CC_BY_NON_COMMERCIAL_4_0: _ModelLicense.ValueType  # 11
    """Commercial use prohibited"""
    MODEL_LICENSE_OTHER_NON_COMMERCIAL: _ModelLicense.ValueType  # 12
    MODEL_LICENSE_LLAMA2: _ModelLicense.ValueType  # 13
    """Licenses for specific models"""
    MODEL_LICENSE_LLAMA3: _ModelLicense.ValueType  # 14
    MODEL_LICENSE_TAIDE: _ModelLicense.ValueType  # 15
    MODEL_LICENSE_FALCON3: _ModelLicense.ValueType  # 16
    MODEL_LICENSE_GEMMA: _ModelLicense.ValueType  # 17
    MODEL_LICENSE_LFM1_0: _ModelLicense.ValueType  # 18
    MODEL_LICENSE_AIMET_MODEL_ZOO: _ModelLicense.ValueType  # 19

class ModelLicense(_ModelLicense, metaclass=_ModelLicenseEnumTypeWrapper): ...

MODEL_LICENSE_UNSPECIFIED: ModelLicense.ValueType  # 0
MODEL_LICENSE_UNLICENSED: ModelLicense.ValueType  # 1
"""General"""
MODEL_LICENSE_COMMERCIAL: ModelLicense.ValueType  # 2
MODEL_LICENSE_AI_HUB_MODELS_LICENSE: ModelLicense.ValueType  # 3
MODEL_LICENSE_APACHE_2_0: ModelLicense.ValueType  # 4
"""Non-restrictive"""
MODEL_LICENSE_MIT: ModelLicense.ValueType  # 5
MODEL_LICENSE_BSD_3_CLAUSE: ModelLicense.ValueType  # 6
MODEL_LICENSE_CC_BY_4_0: ModelLicense.ValueType  # 7
MODEL_LICENSE_AGPL_3_0: ModelLicense.ValueType  # 8
"""Copyleft (derivative works must have the same license)"""
MODEL_LICENSE_GPL_3_0: ModelLicense.ValueType  # 9
MODEL_LICENSE_CREATIVEML_OPENRAIL_M: ModelLicense.ValueType  # 10
MODEL_LICENSE_CC_BY_NON_COMMERCIAL_4_0: ModelLicense.ValueType  # 11
"""Commercial use prohibited"""
MODEL_LICENSE_OTHER_NON_COMMERCIAL: ModelLicense.ValueType  # 12
MODEL_LICENSE_LLAMA2: ModelLicense.ValueType  # 13
"""Licenses for specific models"""
MODEL_LICENSE_LLAMA3: ModelLicense.ValueType  # 14
MODEL_LICENSE_TAIDE: ModelLicense.ValueType  # 15
MODEL_LICENSE_FALCON3: ModelLicense.ValueType  # 16
MODEL_LICENSE_GEMMA: ModelLicense.ValueType  # 17
MODEL_LICENSE_LFM1_0: ModelLicense.ValueType  # 18
MODEL_LICENSE_AIMET_MODEL_ZOO: ModelLicense.ValueType  # 19
global___ModelLicense = ModelLicense

class _ModelDomain:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ModelDomainEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ModelDomain.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MODEL_DOMAIN_UNSPECIFIED: _ModelDomain.ValueType  # 0
    MODEL_DOMAIN_COMPUTER_VISION: _ModelDomain.ValueType  # 1
    MODEL_DOMAIN_MULTIMODAL: _ModelDomain.ValueType  # 2
    MODEL_DOMAIN_AUDIO: _ModelDomain.ValueType  # 3
    MODEL_DOMAIN_GENERATIVE_AI: _ModelDomain.ValueType  # 4

class ModelDomain(_ModelDomain, metaclass=_ModelDomainEnumTypeWrapper): ...

MODEL_DOMAIN_UNSPECIFIED: ModelDomain.ValueType  # 0
MODEL_DOMAIN_COMPUTER_VISION: ModelDomain.ValueType  # 1
MODEL_DOMAIN_MULTIMODAL: ModelDomain.ValueType  # 2
MODEL_DOMAIN_AUDIO: ModelDomain.ValueType  # 3
MODEL_DOMAIN_GENERATIVE_AI: ModelDomain.ValueType  # 4
global___ModelDomain = ModelDomain

class _ModelTag:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ModelTagEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ModelTag.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MODEL_TAG_UNSPECIFIED: _ModelTag.ValueType  # 0
    MODEL_TAG_BACKBONE: _ModelTag.ValueType  # 1
    MODEL_TAG_REAL_TIME: _ModelTag.ValueType  # 2
    MODEL_TAG_FOUNDATION: _ModelTag.ValueType  # 3
    MODEL_TAG_LLM: _ModelTag.ValueType  # 4
    MODEL_TAG_GENERATIVE_AI: _ModelTag.ValueType  # 5
    MODEL_TAG_BU_IOT: _ModelTag.ValueType  # 6
    MODEL_TAG_BU_AUTO: _ModelTag.ValueType  # 7
    MODEL_TAG_BU_COMPUTE: _ModelTag.ValueType  # 8
    MODEL_TAG_MOE: _ModelTag.ValueType  # 9

class ModelTag(_ModelTag, metaclass=_ModelTagEnumTypeWrapper): ...

MODEL_TAG_UNSPECIFIED: ModelTag.ValueType  # 0
MODEL_TAG_BACKBONE: ModelTag.ValueType  # 1
MODEL_TAG_REAL_TIME: ModelTag.ValueType  # 2
MODEL_TAG_FOUNDATION: ModelTag.ValueType  # 3
MODEL_TAG_LLM: ModelTag.ValueType  # 4
MODEL_TAG_GENERATIVE_AI: ModelTag.ValueType  # 5
MODEL_TAG_BU_IOT: ModelTag.ValueType  # 6
MODEL_TAG_BU_AUTO: ModelTag.ValueType  # 7
MODEL_TAG_BU_COMPUTE: ModelTag.ValueType  # 8
MODEL_TAG_MOE: ModelTag.ValueType  # 9
global___ModelTag = ModelTag

class _ModelStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ModelStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ModelStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MODEL_STATUS_UNSPECIFIED: _ModelStatus.ValueType  # 0
    MODEL_STATUS_PUBLISHED: _ModelStatus.ValueType  # 1
    MODEL_STATUS_UNPUBLISHED: _ModelStatus.ValueType  # 2
    MODEL_STATUS_PENDING: _ModelStatus.ValueType  # 3
    """Pending models are waiting for scorecard to collect perf data before being published."""

class ModelStatus(_ModelStatus, metaclass=_ModelStatusEnumTypeWrapper): ...

MODEL_STATUS_UNSPECIFIED: ModelStatus.ValueType  # 0
MODEL_STATUS_PUBLISHED: ModelStatus.ValueType  # 1
MODEL_STATUS_UNPUBLISHED: ModelStatus.ValueType  # 2
MODEL_STATUS_PENDING: ModelStatus.ValueType  # 3
"""Pending models are waiting for scorecard to collect perf data before being published."""
global___ModelStatus = ModelStatus

class _ModelUseCase:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ModelUseCaseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ModelUseCase.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MODEL_USE_CASE_UNSPECIFIED: _ModelUseCase.ValueType  # 0
    MODEL_USE_CASE_IMAGE_CLASSIFICATION: _ModelUseCase.ValueType  # 1
    """Image"""
    MODEL_USE_CASE_IMAGE_EDITING: _ModelUseCase.ValueType  # 2
    MODEL_USE_CASE_IMAGE_GENERATION: _ModelUseCase.ValueType  # 3
    MODEL_USE_CASE_SUPER_RESOLUTION: _ModelUseCase.ValueType  # 4
    MODEL_USE_CASE_SEMANTIC_SEGMENTATION: _ModelUseCase.ValueType  # 5
    MODEL_USE_CASE_DEPTH_ESTIMATION: _ModelUseCase.ValueType  # 6
    MODEL_USE_CASE_GAZE_ESTIMATION: _ModelUseCase.ValueType  # 7
    MODEL_USE_CASE_IMAGE_TO_TEXT: _ModelUseCase.ValueType  # 8
    """E.g. OCR, image caption"""
    MODEL_USE_CASE_OBJECT_DETECTION: _ModelUseCase.ValueType  # 9
    MODEL_USE_CASE_POSE_ESTIMATION: _ModelUseCase.ValueType  # 10
    MODEL_USE_CASE_DRIVER_ASSISTANCE: _ModelUseCase.ValueType  # 11
    MODEL_USE_CASE_ROBOTICS: _ModelUseCase.ValueType  # 12
    MODEL_USE_CASE_SPEECH_RECOGNITION: _ModelUseCase.ValueType  # 13
    """Audio"""
    MODEL_USE_CASE_AUDIO_ENHANCEMENT: _ModelUseCase.ValueType  # 14
    MODEL_USE_CASE_AUDIO_CLASSIFICATION: _ModelUseCase.ValueType  # 15
    MODEL_USE_CASE_AUDIO_GENERATION: _ModelUseCase.ValueType  # 16
    MODEL_USE_CASE_VIDEO_CLASSIFICATION: _ModelUseCase.ValueType  # 17
    """Video"""
    MODEL_USE_CASE_VIDEO_GENERATION: _ModelUseCase.ValueType  # 18
    MODEL_USE_CASE_VIDEO_OBJECT_TRACKING: _ModelUseCase.ValueType  # 19
    MODEL_USE_CASE_TEXT_GENERATION: _ModelUseCase.ValueType  # 20
    """LLM"""

class ModelUseCase(_ModelUseCase, metaclass=_ModelUseCaseEnumTypeWrapper): ...

MODEL_USE_CASE_UNSPECIFIED: ModelUseCase.ValueType  # 0
MODEL_USE_CASE_IMAGE_CLASSIFICATION: ModelUseCase.ValueType  # 1
"""Image"""
MODEL_USE_CASE_IMAGE_EDITING: ModelUseCase.ValueType  # 2
MODEL_USE_CASE_IMAGE_GENERATION: ModelUseCase.ValueType  # 3
MODEL_USE_CASE_SUPER_RESOLUTION: ModelUseCase.ValueType  # 4
MODEL_USE_CASE_SEMANTIC_SEGMENTATION: ModelUseCase.ValueType  # 5
MODEL_USE_CASE_DEPTH_ESTIMATION: ModelUseCase.ValueType  # 6
MODEL_USE_CASE_GAZE_ESTIMATION: ModelUseCase.ValueType  # 7
MODEL_USE_CASE_IMAGE_TO_TEXT: ModelUseCase.ValueType  # 8
"""E.g. OCR, image caption"""
MODEL_USE_CASE_OBJECT_DETECTION: ModelUseCase.ValueType  # 9
MODEL_USE_CASE_POSE_ESTIMATION: ModelUseCase.ValueType  # 10
MODEL_USE_CASE_DRIVER_ASSISTANCE: ModelUseCase.ValueType  # 11
MODEL_USE_CASE_ROBOTICS: ModelUseCase.ValueType  # 12
MODEL_USE_CASE_SPEECH_RECOGNITION: ModelUseCase.ValueType  # 13
"""Audio"""
MODEL_USE_CASE_AUDIO_ENHANCEMENT: ModelUseCase.ValueType  # 14
MODEL_USE_CASE_AUDIO_CLASSIFICATION: ModelUseCase.ValueType  # 15
MODEL_USE_CASE_AUDIO_GENERATION: ModelUseCase.ValueType  # 16
MODEL_USE_CASE_VIDEO_CLASSIFICATION: ModelUseCase.ValueType  # 17
"""Video"""
MODEL_USE_CASE_VIDEO_GENERATION: ModelUseCase.ValueType  # 18
MODEL_USE_CASE_VIDEO_OBJECT_TRACKING: ModelUseCase.ValueType  # 19
MODEL_USE_CASE_TEXT_GENERATION: ModelUseCase.ValueType  # 20
"""LLM"""
global___ModelUseCase = ModelUseCase

@typing.final
class ModelInfo(google.protobuf.message.Message):
    """Schema for model info.yaml."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TechnicalDetail(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        STRING_VALUE_FIELD_NUMBER: builtins.int
        INT_VALUE_FIELD_NUMBER: builtins.int
        FLOAT_VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        string_value: builtins.str
        int_value: builtins.int
        float_value: builtins.float
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            string_value: builtins.str = ...,
            int_value: builtins.int = ...,
            float_value: builtins.float = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["float_value", b"float_value", "int_value", b"int_value", "string_value", b"string_value", "value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["float_value", b"float_value", "int_value", b"int_value", "key", b"key", "string_value", b"string_value", "value", b"value"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["value", b"value"]) -> typing.Literal["string_value", "int_value", "float_value"] | None: ...

    @typing.final
    class LLMDetails(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        class _CallToAction:
            ValueType = typing.NewType("ValueType", builtins.int)
            V: typing_extensions.TypeAlias = ValueType

        class _CallToActionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[ModelInfo.LLMDetails._CallToAction.ValueType], builtins.type):
            DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
            CALL_TO_ACTION_UNSPECIFIED: ModelInfo.LLMDetails._CallToAction.ValueType  # 0
            CALL_TO_ACTION_DOWNLOAD: ModelInfo.LLMDetails._CallToAction.ValueType  # 1
            CALL_TO_ACTION_VIEW_README: ModelInfo.LLMDetails._CallToAction.ValueType  # 2
            CALL_TO_ACTION_DOWNLOAD_AND_VIEW_README: ModelInfo.LLMDetails._CallToAction.ValueType  # 3
            CALL_TO_ACTION_CONTACT_FOR_PURCHASE: ModelInfo.LLMDetails._CallToAction.ValueType  # 4
            CALL_TO_ACTION_CONTACT_FOR_DOWNLOAD: ModelInfo.LLMDetails._CallToAction.ValueType  # 5
            CALL_TO_ACTION_COMING_SOON: ModelInfo.LLMDetails._CallToAction.ValueType  # 6
            CALL_TO_ACTION_CONTACT_US: ModelInfo.LLMDetails._CallToAction.ValueType  # 7

        class CallToAction(_CallToAction, metaclass=_CallToActionEnumTypeWrapper): ...
        CALL_TO_ACTION_UNSPECIFIED: ModelInfo.LLMDetails.CallToAction.ValueType  # 0
        CALL_TO_ACTION_DOWNLOAD: ModelInfo.LLMDetails.CallToAction.ValueType  # 1
        CALL_TO_ACTION_VIEW_README: ModelInfo.LLMDetails.CallToAction.ValueType  # 2
        CALL_TO_ACTION_DOWNLOAD_AND_VIEW_README: ModelInfo.LLMDetails.CallToAction.ValueType  # 3
        CALL_TO_ACTION_CONTACT_FOR_PURCHASE: ModelInfo.LLMDetails.CallToAction.ValueType  # 4
        CALL_TO_ACTION_CONTACT_FOR_DOWNLOAD: ModelInfo.LLMDetails.CallToAction.ValueType  # 5
        CALL_TO_ACTION_COMING_SOON: ModelInfo.LLMDetails.CallToAction.ValueType  # 6
        CALL_TO_ACTION_CONTACT_US: ModelInfo.LLMDetails.CallToAction.ValueType  # 7

        CALL_TO_ACTION_FIELD_NUMBER: builtins.int
        GENIE_COMPATIBLE_FIELD_NUMBER: builtins.int
        LLAMA_CPP_COMPATIBLE_FIELD_NUMBER: builtins.int
        LLAMA_CPP_MODEL_URL_FIELD_NUMBER: builtins.int
        call_to_action: global___ModelInfo.LLMDetails.CallToAction.ValueType
        genie_compatible: builtins.bool
        """Genie (QNN context binary) support"""
        llama_cpp_compatible: builtins.bool
        """llama.cpp support
        Whether the model runs with llama.cpp. If true, llama_cpp_model_url must be set.
        """
        llama_cpp_model_url: builtins.str
        """Global llama.cpp model URL — used when genie_compatible is false.
        This allows specifying the URL once instead of per device.
        """
        def __init__(
            self,
            *,
            call_to_action: global___ModelInfo.LLMDetails.CallToAction.ValueType = ...,
            genie_compatible: builtins.bool = ...,
            llama_cpp_compatible: builtins.bool = ...,
            llama_cpp_model_url: builtins.str | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_llama_cpp_model_url", b"_llama_cpp_model_url", "llama_cpp_model_url", b"llama_cpp_model_url"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_llama_cpp_model_url", b"_llama_cpp_model_url", "call_to_action", b"call_to_action", "genie_compatible", b"genie_compatible", "llama_cpp_compatible", b"llama_cpp_compatible", "llama_cpp_model_url", b"llama_cpp_model_url"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_llama_cpp_model_url", b"_llama_cpp_model_url"]) -> typing.Literal["llama_cpp_model_url"] | None: ...

    AIHM_VERSION_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    STATUS_REASON_FIELD_NUMBER: builtins.int
    HEADLINE_FIELD_NUMBER: builtins.int
    DOMAIN_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    USE_CASE_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    APPLICABLE_SCENARIOS_FIELD_NUMBER: builtins.int
    RELATED_MODELS_FIELD_NUMBER: builtins.int
    FORM_FACTORS_FIELD_NUMBER: builtins.int
    TECHNICAL_DETAILS_FIELD_NUMBER: builtins.int
    LICENSE_TYPE_FIELD_NUMBER: builtins.int
    MODEL_MAKER_ID_FIELD_NUMBER: builtins.int
    DATASET_FIELD_NUMBER: builtins.int
    RESEARCH_PAPER_FIELD_NUMBER: builtins.int
    RESEARCH_PAPER_TITLE_FIELD_NUMBER: builtins.int
    SOURCE_REPO_FIELD_NUMBER: builtins.int
    LICENSE_URL_FIELD_NUMBER: builtins.int
    HAS_STATIC_BANNER_FIELD_NUMBER: builtins.int
    HAS_ANIMATED_BANNER_FIELD_NUMBER: builtins.int
    IMSDK_SUPPORTED_FIELD_NUMBER: builtins.int
    RESTRICT_MODEL_SHARING_FIELD_NUMBER: builtins.int
    NUMERICS_BENCHMARK_FIELD_NUMBER: builtins.int
    MODEL_TYPE_LLM_FIELD_NUMBER: builtins.int
    LLM_DETAILS_FIELD_NUMBER: builtins.int
    PRIVATE_PERF_FORM_FACTORS_FIELD_NUMBER: builtins.int
    aihm_version: builtins.str
    id: builtins.str
    """---------------------------------------------------------------------------
    Identity
    ---------------------------------------------------------------------------
    Name of the model's folder within the repo.
    """
    name: builtins.str
    """Name of the model as it will appear on the website.
    Should have dashes instead of underscores and all
    words capitalized. For example, `Whisper-Base-En`.
    """
    status: global___ModelStatus.ValueType
    """Whether or not the model is published on the website.
    This should be set to public unless the model has poor accuracy/perf.
    """
    status_reason: builtins.str
    """If status is private, this must have a reference to an issue with an explanation."""
    headline: builtins.str
    """---------------------------------------------------------------------------
    Description & categorization
    ---------------------------------------------------------------------------

    A brief catchy headline explaining what the model does and why it may be interesting.
    """
    domain: global___ModelDomain.ValueType
    """The domain the model is used in such as computer vision, audio, etc."""
    description: builtins.str
    """A 2-3 sentence description of how the model can be used."""
    use_case: global___ModelUseCase.ValueType
    """What task the model is used to solve, such as object detection, classification, etc."""
    license_type: global___ModelLicense.ValueType
    """The license type of the original model repo."""
    model_maker_id: builtins.str
    """Some models are made by a company."""
    research_paper: builtins.str
    """---------------------------------------------------------------------------
    References
    ---------------------------------------------------------------------------

    Link to the research paper where the model was first published. Usually an arxiv link.
    """
    research_paper_title: builtins.str
    """The title of the research paper."""
    source_repo: builtins.str
    """A link to the original github repo with the model's code."""
    license_url: builtins.str
    """A link to the model's license. Most commonly found in the github repo it was cloned from."""
    has_static_banner: builtins.bool
    """---------------------------------------------------------------------------
    Branding
    ---------------------------------------------------------------------------

    Whether the model has a static image uploaded in S3. All published models must have this.
    """
    has_animated_banner: builtins.bool
    """Whether the model has an animated asset uploaded in S3. This is optional."""
    imsdk_supported: builtins.bool
    """---------------------------------------------------------------------------
    Features & deployment
    ---------------------------------------------------------------------------

    Whether the model is compatible with the IMSDK Plugin for IOT devices.
    """
    restrict_model_sharing: builtins.bool
    """If set, model assets shouldn't be distributed."""
    model_type_llm: builtins.bool
    """---------------------------------------------------------------------------
    LLM-specific
    ---------------------------------------------------------------------------

    Whether it is a large language model (LLM) or not.
    """
    @property
    def tags(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___ModelTag.ValueType]:
        """A list of applicable tags to add to the model."""

    @property
    def applicable_scenarios(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """A list of real-world applications for which this model could be used.
        This is free-form and almost anything reasonable here is fine.
        """

    @property
    def related_models(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """A list of other similar models in the repo.
        Typically, any model that performs the same task is fine.
        If nothing fits, this can be left blank. Limit to 3 models.
        """

    @property
    def form_factors(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[platform_pb2.FormFactor.ValueType]:
        """A list of device types for which this model could be useful.
        If unsure what to put here, default to Phone and Tablet.
        """

    @property
    def technical_details(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ModelInfo.TechnicalDetail]:
        """---------------------------------------------------------------------------
        Metadata
        ---------------------------------------------------------------------------

        A list of a few technical details about the model.
          Model checkpoint: The name of the downloaded model checkpoint file.
          Input resolution: The size of the model's input. For example, `2048x1024`.
          Number of parameters: The number of parameters in the model.
          Model size: The file size of the downloaded model asset.
          Number of output classes: The number of classes the model can classify or annotate.
        """

    @property
    def dataset(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """A list of datasets for which the model has pre-trained checkpoints
        available as options in `model.py`. Typically only has one entry.
        """

    @property
    def numerics_benchmark(self) -> numerics_pb2.NumericsAccuracyBenchmark:
        """---------------------------------------------------------------------------
        Validation
        ---------------------------------------------------------------------------

        Expected accuracy benchmark. If set, scorecard will flag results that
        deviate from this value by more than the metric's metric_enablement_threshold.
        """

    @property
    def llm_details(self) -> global___ModelInfo.LLMDetails: ...
    @property
    def private_perf_form_factors(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[platform_pb2.FormFactor.ValueType]:
        """Device form factors for which we don't publish performance data."""

    def __init__(
        self,
        *,
        aihm_version: builtins.str = ...,
        id: builtins.str = ...,
        name: builtins.str = ...,
        status: global___ModelStatus.ValueType = ...,
        status_reason: builtins.str | None = ...,
        headline: builtins.str = ...,
        domain: global___ModelDomain.ValueType = ...,
        description: builtins.str = ...,
        use_case: global___ModelUseCase.ValueType = ...,
        tags: collections.abc.Iterable[global___ModelTag.ValueType] | None = ...,
        applicable_scenarios: collections.abc.Iterable[builtins.str] | None = ...,
        related_models: collections.abc.Iterable[builtins.str] | None = ...,
        form_factors: collections.abc.Iterable[platform_pb2.FormFactor.ValueType] | None = ...,
        technical_details: collections.abc.Iterable[global___ModelInfo.TechnicalDetail] | None = ...,
        license_type: global___ModelLicense.ValueType = ...,
        model_maker_id: builtins.str | None = ...,
        dataset: collections.abc.Iterable[builtins.str] | None = ...,
        research_paper: builtins.str | None = ...,
        research_paper_title: builtins.str | None = ...,
        source_repo: builtins.str | None = ...,
        license_url: builtins.str | None = ...,
        has_static_banner: builtins.bool = ...,
        has_animated_banner: builtins.bool = ...,
        imsdk_supported: builtins.bool = ...,
        restrict_model_sharing: builtins.bool = ...,
        numerics_benchmark: numerics_pb2.NumericsAccuracyBenchmark | None = ...,
        model_type_llm: builtins.bool = ...,
        llm_details: global___ModelInfo.LLMDetails | None = ...,
        private_perf_form_factors: collections.abc.Iterable[platform_pb2.FormFactor.ValueType] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_license_url", b"_license_url", "_llm_details", b"_llm_details", "_model_maker_id", b"_model_maker_id", "_numerics_benchmark", b"_numerics_benchmark", "_research_paper", b"_research_paper", "_research_paper_title", b"_research_paper_title", "_source_repo", b"_source_repo", "_status_reason", b"_status_reason", "license_url", b"license_url", "llm_details", b"llm_details", "model_maker_id", b"model_maker_id", "numerics_benchmark", b"numerics_benchmark", "research_paper", b"research_paper", "research_paper_title", b"research_paper_title", "source_repo", b"source_repo", "status_reason", b"status_reason"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_license_url", b"_license_url", "_llm_details", b"_llm_details", "_model_maker_id", b"_model_maker_id", "_numerics_benchmark", b"_numerics_benchmark", "_research_paper", b"_research_paper", "_research_paper_title", b"_research_paper_title", "_source_repo", b"_source_repo", "_status_reason", b"_status_reason", "aihm_version", b"aihm_version", "applicable_scenarios", b"applicable_scenarios", "dataset", b"dataset", "description", b"description", "domain", b"domain", "form_factors", b"form_factors", "has_animated_banner", b"has_animated_banner", "has_static_banner", b"has_static_banner", "headline", b"headline", "id", b"id", "imsdk_supported", b"imsdk_supported", "license_type", b"license_type", "license_url", b"license_url", "llm_details", b"llm_details", "model_maker_id", b"model_maker_id", "model_type_llm", b"model_type_llm", "name", b"name", "numerics_benchmark", b"numerics_benchmark", "private_perf_form_factors", b"private_perf_form_factors", "related_models", b"related_models", "research_paper", b"research_paper", "research_paper_title", b"research_paper_title", "restrict_model_sharing", b"restrict_model_sharing", "source_repo", b"source_repo", "status", b"status", "status_reason", b"status_reason", "tags", b"tags", "technical_details", b"technical_details", "use_case", b"use_case"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_license_url", b"_license_url"]) -> typing.Literal["license_url"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_llm_details", b"_llm_details"]) -> typing.Literal["llm_details"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_model_maker_id", b"_model_maker_id"]) -> typing.Literal["model_maker_id"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_numerics_benchmark", b"_numerics_benchmark"]) -> typing.Literal["numerics_benchmark"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_research_paper", b"_research_paper"]) -> typing.Literal["research_paper"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_research_paper_title", b"_research_paper_title"]) -> typing.Literal["research_paper_title"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_source_repo", b"_source_repo"]) -> typing.Literal["source_repo"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_status_reason", b"_status_reason"]) -> typing.Literal["status_reason"] | None: ...

global___ModelInfo = ModelInfo
