# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: manifest.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qai_hub_models_cli.proto import info_pb2 as info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emanifest.proto\x12\x05qaihm\x1a\ninfo.proto\"Y\n\x11ModelManifestUrls\x12\x0c\n\x04info\x18\x01 \x01(\t\x12\x0c\n\x04perf\x18\x02 \x01(\t\x12\x10\n\x08numerics\x18\x03 \x01(\t\x12\x16\n\x0erelease_assets\x18\x04 \x01(\t\"\x8b\x01\n\x12ManifestModelEntry\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x02 \x01(\t\x12\"\n\x06\x64omain\x18\x03 \x01(\x0e\x32\x12.qaihm.ModelDomain\x12/\n\rmanifest_urls\x18\x04 \x01(\x0b\x32\x18.qaihm.ModelManifestUrls\"c\n\x0fReleaseManifest\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x14\n\x0cplatform_url\x18\x02 \x01(\t\x12)\n\x06models\x18\x03 \x03(\x0b\x32\x19.qaihm.ManifestModelEntryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manifest_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MODELMANIFESTURLS']._serialized_start=37
  _globals['_MODELMANIFESTURLS']._serialized_end=126
  _globals['_MANIFESTMODELENTRY']._serialized_start=129
  _globals['_MANIFESTMODELENTRY']._serialized_end=268
  _globals['_RELEASEMANIFEST']._serialized_start=270
  _globals['_RELEASEMANIFEST']._serialized_end=369
# @@protoc_insertion_point(module_scope)
