# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
SPDX-License-Identifier: BSD-3-Clause
---------------------------------------------------------------------

Metadata schema for model I/O specifications.

Defines the structure for metadata.json files that document
model input/output specifications and quantization parameters for a single
exported model.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
from qai_hub_models_cli.proto import platform_pb2
import shared.precision_pb2
import shared.runtime_pb2
import shared.tensor_spec_pb2
import shared.tool_versions_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ModelFileMetadata(google.protobuf.message.Message):
    """Metadata for a single exported model file.

    Represents the I/O specifications for one exported model component,
    including input/output tensor shapes, dtypes, and quantization parameters.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILENAME_FIELD_NUMBER: builtins.int
    INPUTS_FIELD_NUMBER: builtins.int
    OUTPUTS_FIELD_NUMBER: builtins.int
    filename: builtins.str
    @property
    def inputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[shared.tensor_spec_pb2.TensorSpec]: ...
    @property
    def outputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[shared.tensor_spec_pb2.TensorSpec]: ...
    def __init__(
        self,
        *,
        filename: builtins.str = ...,
        inputs: collections.abc.Iterable[shared.tensor_spec_pb2.TensorSpec] | None = ...,
        outputs: collections.abc.Iterable[shared.tensor_spec_pb2.TensorSpec] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["filename", b"filename", "inputs", b"inputs", "outputs", b"outputs"]) -> None: ...

global___ModelFileMetadata = ModelFileMetadata

@typing.final
class SupplementaryFileMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILENAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    filename: builtins.str
    description: builtins.str
    def __init__(
        self,
        *,
        filename: builtins.str = ...,
        description: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["description", b"description", "filename", b"filename"]) -> None: ...

global___SupplementaryFileMetadata = SupplementaryFileMetadata

@typing.final
class GenieChatTemplate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GLOBAL_PREFIX_FIELD_NUMBER: builtins.int
    SYSTEM_PREFIX_FIELD_NUMBER: builtins.int
    SYSTEM_SUFFIX_FIELD_NUMBER: builtins.int
    USER_PREFIX_FIELD_NUMBER: builtins.int
    USER_SUFFIX_FIELD_NUMBER: builtins.int
    ASSISTANT_PREFIX_FIELD_NUMBER: builtins.int
    ASSISTANT_SUFFIX_FIELD_NUMBER: builtins.int
    VISION_START_FIELD_NUMBER: builtins.int
    VISION_END_FIELD_NUMBER: builtins.int
    DEFAULT_SYSTEM_PROMPT_FIELD_NUMBER: builtins.int
    global_prefix: builtins.str
    system_prefix: builtins.str
    system_suffix: builtins.str
    user_prefix: builtins.str
    user_suffix: builtins.str
    assistant_prefix: builtins.str
    assistant_suffix: builtins.str
    vision_start: builtins.str
    vision_end: builtins.str
    default_system_prompt: builtins.str
    def __init__(
        self,
        *,
        global_prefix: builtins.str = ...,
        system_prefix: builtins.str = ...,
        system_suffix: builtins.str = ...,
        user_prefix: builtins.str = ...,
        user_suffix: builtins.str = ...,
        assistant_prefix: builtins.str = ...,
        assistant_suffix: builtins.str = ...,
        vision_start: builtins.str = ...,
        vision_end: builtins.str = ...,
        default_system_prompt: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["assistant_prefix", b"assistant_prefix", "assistant_suffix", b"assistant_suffix", "default_system_prompt", b"default_system_prompt", "global_prefix", b"global_prefix", "system_prefix", b"system_prefix", "system_suffix", b"system_suffix", "user_prefix", b"user_prefix", "user_suffix", b"user_suffix", "vision_end", b"vision_end", "vision_start", b"vision_start"]) -> None: ...

global___GenieChatTemplate = GenieChatTemplate

@typing.final
class GenieMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class GeniePipeline(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class NodesEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            value: builtins.str
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

        @typing.final
        class GeniePipelineConnection(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            PRODUCER_NODE_FIELD_NUMBER: builtins.int
            PRODUCER_NODE_IO_FIELD_NUMBER: builtins.int
            CONSUMER_NODE_FIELD_NUMBER: builtins.int
            CONSUMER_NODE_IO_FIELD_NUMBER: builtins.int
            producer_node: builtins.str
            producer_node_io: builtins.str
            consumer_node: builtins.str
            consumer_node_io: builtins.str
            def __init__(
                self,
                *,
                producer_node: builtins.str = ...,
                producer_node_io: builtins.str = ...,
                consumer_node: builtins.str = ...,
                consumer_node_io: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["consumer_node", b"consumer_node", "consumer_node_io", b"consumer_node_io", "producer_node", b"producer_node", "producer_node_io", b"producer_node_io"]) -> None: ...

        NODES_FIELD_NUMBER: builtins.int
        CONNECTIONS_FIELD_NUMBER: builtins.int
        @property
        def nodes(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
        @property
        def connections(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GenieMetadata.GeniePipeline.GeniePipelineConnection]: ...
        def __init__(
            self,
            *,
            nodes: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
            connections: collections.abc.Iterable[global___GenieMetadata.GeniePipeline.GeniePipelineConnection] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["connections", b"connections", "nodes", b"nodes"]) -> None: ...

    @typing.final
    class GenieSampleInput(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NODE_FIELD_NUMBER: builtins.int
        NODE_IO_FIELD_NUMBER: builtins.int
        FILE_FIELD_NUMBER: builtins.int
        node: builtins.str
        node_io: builtins.str
        file: builtins.str
        def __init__(
            self,
            *,
            node: builtins.str = ...,
            node_io: builtins.str = ...,
            file: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["file", b"file", "node", b"node", "node_io", b"node_io"]) -> None: ...

    @typing.final
    class GenieVisionPreprocessing(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        IMAGE_WIDTH_FIELD_NUMBER: builtins.int
        IMAGE_HEIGHT_FIELD_NUMBER: builtins.int
        PATCH_SIZE_FIELD_NUMBER: builtins.int
        TEMPORAL_PATCH_SIZE_FIELD_NUMBER: builtins.int
        SPATIAL_MERGE_SIZE_FIELD_NUMBER: builtins.int
        NORMALIZE_MEAN_FIELD_NUMBER: builtins.int
        NORMALIZE_STD_FIELD_NUMBER: builtins.int
        image_width: builtins.int
        image_height: builtins.int
        patch_size: builtins.int
        temporal_patch_size: builtins.int
        spatial_merge_size: builtins.int
        @property
        def normalize_mean(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
        @property
        def normalize_std(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
        def __init__(
            self,
            *,
            image_width: builtins.int = ...,
            image_height: builtins.int = ...,
            patch_size: builtins.int = ...,
            temporal_patch_size: builtins.int = ...,
            spatial_merge_size: builtins.int = ...,
            normalize_mean: collections.abc.Iterable[builtins.float] | None = ...,
            normalize_std: collections.abc.Iterable[builtins.float] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["image_height", b"image_height", "image_width", b"image_width", "normalize_mean", b"normalize_mean", "normalize_std", b"normalize_std", "patch_size", b"patch_size", "spatial_merge_size", b"spatial_merge_size", "temporal_patch_size", b"temporal_patch_size"]) -> None: ...

    CHAT_TEMPLATE_FIELD_NUMBER: builtins.int
    CONTEXT_LENGTHS_FIELD_NUMBER: builtins.int
    SUPPORTS_STREAMING_FIELD_NUMBER: builtins.int
    SUPPORTS_VISION_FIELD_NUMBER: builtins.int
    PIPELINE_FIELD_NUMBER: builtins.int
    SAMPLE_INPUTS_FIELD_NUMBER: builtins.int
    VISION_PREPROCESSING_FIELD_NUMBER: builtins.int
    SUPPORTS_THINKING_FIELD_NUMBER: builtins.int
    supports_streaming: builtins.bool
    supports_vision: builtins.bool
    supports_thinking: builtins.bool
    @property
    def chat_template(self) -> global___GenieChatTemplate: ...
    @property
    def context_lengths(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def pipeline(self) -> global___GenieMetadata.GeniePipeline: ...
    @property
    def sample_inputs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___GenieMetadata.GenieSampleInput]: ...
    @property
    def vision_preprocessing(self) -> global___GenieMetadata.GenieVisionPreprocessing: ...
    def __init__(
        self,
        *,
        chat_template: global___GenieChatTemplate | None = ...,
        context_lengths: collections.abc.Iterable[builtins.int] | None = ...,
        supports_streaming: builtins.bool = ...,
        supports_vision: builtins.bool = ...,
        pipeline: global___GenieMetadata.GeniePipeline | None = ...,
        sample_inputs: collections.abc.Iterable[global___GenieMetadata.GenieSampleInput] | None = ...,
        vision_preprocessing: global___GenieMetadata.GenieVisionPreprocessing | None = ...,
        supports_thinking: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_pipeline", b"_pipeline", "_vision_preprocessing", b"_vision_preprocessing", "chat_template", b"chat_template", "pipeline", b"pipeline", "vision_preprocessing", b"vision_preprocessing"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_pipeline", b"_pipeline", "_vision_preprocessing", b"_vision_preprocessing", "chat_template", b"chat_template", "context_lengths", b"context_lengths", "pipeline", b"pipeline", "sample_inputs", b"sample_inputs", "supports_streaming", b"supports_streaming", "supports_thinking", b"supports_thinking", "supports_vision", b"supports_vision", "vision_preprocessing", b"vision_preprocessing"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_pipeline", b"_pipeline"]) -> typing.Literal["pipeline"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_vision_preprocessing", b"_vision_preprocessing"]) -> typing.Literal["vision_preprocessing"] | None: ...

global___GenieMetadata = GenieMetadata

@typing.final
class ModelMetadata(google.protobuf.message.Message):
    """Metadata for a model that may have multiple model files.

    For single-file models (e.g., ResNet50), this will have one entry.
    For multi-file models (e.g., Stable Diffusion with text_encoder.bin, unet.bin, vae_decoder.bin),
    this will have multiple entries mapping model file names to their metadata.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AIHM_VERSION_FIELD_NUMBER: builtins.int
    MODEL_ID_FIELD_NUMBER: builtins.int
    MODEL_NAME_FIELD_NUMBER: builtins.int
    RUNTIME_FIELD_NUMBER: builtins.int
    PRECISION_FIELD_NUMBER: builtins.int
    TOOL_VERSIONS_FIELD_NUMBER: builtins.int
    MODEL_FILES_FIELD_NUMBER: builtins.int
    SUPPLEMENTARY_FILES_FIELD_NUMBER: builtins.int
    GENIE_FIELD_NUMBER: builtins.int
    CHIPSET_ATTRIBUTES_FIELD_NUMBER: builtins.int
    aihm_version: builtins.str
    model_id: builtins.str
    model_name: builtins.str
    runtime: shared.runtime_pb2.Runtime.ValueType
    """Export configuration"""
    precision: shared.precision_pb2.Precision.ValueType
    @property
    def tool_versions(self) -> shared.tool_versions_pb2.ToolVersions: ...
    @property
    def model_files(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ModelFileMetadata]:
        """Model files & supplementary data"""

    @property
    def supplementary_files(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SupplementaryFileMetadata]:
        """Optional list of supplementary files included in the export that are not model files
        (e.g., labels, config files). Can be populated by the model's write_supplementary_files method.
        """

    @property
    def genie(self) -> global___GenieMetadata:
        """Optional Genie SDK metadata for on-device deployment."""

    @property
    def chipset_attributes(self) -> platform_pb2.ChipsetInfo:
        """Chipset attributes relevant to the compiled model asset (AoT only)."""

    def __init__(
        self,
        *,
        aihm_version: builtins.str = ...,
        model_id: builtins.str = ...,
        model_name: builtins.str = ...,
        runtime: shared.runtime_pb2.Runtime.ValueType = ...,
        precision: shared.precision_pb2.Precision.ValueType = ...,
        tool_versions: shared.tool_versions_pb2.ToolVersions | None = ...,
        model_files: collections.abc.Iterable[global___ModelFileMetadata] | None = ...,
        supplementary_files: collections.abc.Iterable[global___SupplementaryFileMetadata] | None = ...,
        genie: global___GenieMetadata | None = ...,
        chipset_attributes: platform_pb2.ChipsetInfo | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_chipset_attributes", b"_chipset_attributes", "_genie", b"_genie", "chipset_attributes", b"chipset_attributes", "genie", b"genie", "tool_versions", b"tool_versions"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_chipset_attributes", b"_chipset_attributes", "_genie", b"_genie", "aihm_version", b"aihm_version", "chipset_attributes", b"chipset_attributes", "genie", b"genie", "model_files", b"model_files", "model_id", b"model_id", "model_name", b"model_name", "precision", b"precision", "runtime", b"runtime", "supplementary_files", b"supplementary_files", "tool_versions", b"tool_versions"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_chipset_attributes", b"_chipset_attributes"]) -> typing.Literal["chipset_attributes"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing.Literal["_genie", b"_genie"]) -> typing.Literal["genie"] | None: ...

global___ModelMetadata = ModelMetadata
