# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
SPDX-License-Identifier: BSD-3-Clause
---------------------------------------------------------------------
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import shared.precision_pb2
import shared.range_pb2
import shared.runtime_pb2
import shared.tool_versions_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ModelPerf(google.protobuf.message.Message):
    """Schema for perf.yaml files."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class PerformanceDetails(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PRECISION_FIELD_NUMBER: builtins.int
        COMPONENT_FIELD_NUMBER: builtins.int
        DEVICE_FIELD_NUMBER: builtins.int
        RUNTIME_FIELD_NUMBER: builtins.int
        TOOL_VERSIONS_FIELD_NUMBER: builtins.int
        PROFILE_JOB_FIELD_NUMBER: builtins.int
        METRICS_FIELD_NUMBER: builtins.int
        LLM_METRICS_FIELD_NUMBER: builtins.int
        precision: shared.precision_pb2.Precision.ValueType
        component: builtins.str
        device: builtins.str
        runtime: shared.runtime_pb2.Runtime.ValueType
        @property
        def tool_versions(self) -> shared.tool_versions_pb2.ToolVersions:
            """The tool versions used to generate these results."""

        @property
        def profile_job(self) -> global___ModelPerf.ProfileJob:
            """Set for all non-LLMs."""

        @property
        def metrics(self) -> global___ModelPerf.PerfMetrics:
            """Set for all non-LLMs, unless profiling fails."""

        @property
        def llm_metrics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ModelPerf.LLMPerfMetrics]:
            """Only used for LLMs."""

        def __init__(
            self,
            *,
            precision: shared.precision_pb2.Precision.ValueType = ...,
            component: builtins.str | None = ...,
            device: builtins.str = ...,
            runtime: shared.runtime_pb2.Runtime.ValueType = ...,
            tool_versions: shared.tool_versions_pb2.ToolVersions | None = ...,
            profile_job: global___ModelPerf.ProfileJob | None = ...,
            metrics: global___ModelPerf.PerfMetrics | None = ...,
            llm_metrics: collections.abc.Iterable[global___ModelPerf.LLMPerfMetrics] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_component", b"_component", "_metrics", b"_metrics", "_profile_job", b"_profile_job", "component", b"component", "metrics", b"metrics", "profile_job", b"profile_job", "tool_versions", b"tool_versions"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_component", b"_component", "_metrics", b"_metrics", "_profile_job", b"_profile_job", "component", b"component", "device", b"device", "llm_metrics", b"llm_metrics", "metrics", b"metrics", "precision", b"precision", "profile_job", b"profile_job", "runtime", b"runtime", "tool_versions", b"tool_versions"]) -> None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_component", b"_component"]) -> typing.Literal["component"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_metrics", b"_metrics"]) -> typing.Literal["metrics"] | None: ...
        @typing.overload
        def WhichOneof(self, oneof_group: typing.Literal["_profile_job", b"_profile_job"]) -> typing.Literal["profile_job"] | None: ...

    @typing.final
    class ProfileJob(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        STATUS_FIELD_NUMBER: builtins.int
        id: builtins.str
        status: builtins.str
        def __init__(
            self,
            *,
            id: builtins.str = ...,
            status: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["id", b"id", "status", b"status"]) -> None: ...

    @typing.final
    class PerfMetrics(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class LayerCounts(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            TOTAL_FIELD_NUMBER: builtins.int
            NPU_FIELD_NUMBER: builtins.int
            GPU_FIELD_NUMBER: builtins.int
            CPU_FIELD_NUMBER: builtins.int
            total: builtins.int
            npu: builtins.int
            gpu: builtins.int
            cpu: builtins.int
            def __init__(
                self,
                *,
                total: builtins.int = ...,
                npu: builtins.int = ...,
                gpu: builtins.int = ...,
                cpu: builtins.int = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["cpu", b"cpu", "gpu", b"gpu", "npu", b"npu", "total", b"total"]) -> None: ...

        INFERENCE_TIME_MILLISECONDS_FIELD_NUMBER: builtins.int
        ESTIMATED_PEAK_MEMORY_RANGE_MB_FIELD_NUMBER: builtins.int
        PRIMARY_COMPUTE_UNIT_FIELD_NUMBER: builtins.int
        LAYER_COUNTS_FIELD_NUMBER: builtins.int
        inference_time_milliseconds: builtins.float
        primary_compute_unit: builtins.str
        @property
        def estimated_peak_memory_range_mb(self) -> shared.range_pb2.IntRange: ...
        @property
        def layer_counts(self) -> global___ModelPerf.PerfMetrics.LayerCounts: ...
        def __init__(
            self,
            *,
            inference_time_milliseconds: builtins.float = ...,
            estimated_peak_memory_range_mb: shared.range_pb2.IntRange | None = ...,
            primary_compute_unit: builtins.str = ...,
            layer_counts: global___ModelPerf.PerfMetrics.LayerCounts | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["estimated_peak_memory_range_mb", b"estimated_peak_memory_range_mb", "layer_counts", b"layer_counts"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["estimated_peak_memory_range_mb", b"estimated_peak_memory_range_mb", "inference_time_milliseconds", b"inference_time_milliseconds", "layer_counts", b"layer_counts", "primary_compute_unit", b"primary_compute_unit"]) -> None: ...

    @typing.final
    class LLMPerfMetrics(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CONTEXT_LENGTH_FIELD_NUMBER: builtins.int
        TOKENS_PER_SECOND_FIELD_NUMBER: builtins.int
        TIME_TO_FIRST_TOKEN_RANGE_MILLISECONDS_FIELD_NUMBER: builtins.int
        context_length: builtins.int
        tokens_per_second: builtins.float
        @property
        def time_to_first_token_range_milliseconds(self) -> shared.range_pb2.DoubleRange: ...
        def __init__(
            self,
            *,
            context_length: builtins.int = ...,
            tokens_per_second: builtins.float = ...,
            time_to_first_token_range_milliseconds: shared.range_pb2.DoubleRange | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_time_to_first_token_range_milliseconds", b"_time_to_first_token_range_milliseconds", "time_to_first_token_range_milliseconds", b"time_to_first_token_range_milliseconds"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_time_to_first_token_range_milliseconds", b"_time_to_first_token_range_milliseconds", "context_length", b"context_length", "time_to_first_token_range_milliseconds", b"time_to_first_token_range_milliseconds", "tokens_per_second", b"tokens_per_second"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_time_to_first_token_range_milliseconds", b"_time_to_first_token_range_milliseconds"]) -> typing.Literal["time_to_first_token_range_milliseconds"] | None: ...

    AIHM_VERSION_FIELD_NUMBER: builtins.int
    MODEL_ID_FIELD_NUMBER: builtins.int
    SUPPORTED_DEVICES_FIELD_NUMBER: builtins.int
    SUPPORTED_CHIPSETS_FIELD_NUMBER: builtins.int
    PERFORMANCE_METRICS_FIELD_NUMBER: builtins.int
    aihm_version: builtins.str
    model_id: builtins.str
    @property
    def supported_devices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def supported_chipsets(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def performance_metrics(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ModelPerf.PerformanceDetails]: ...
    def __init__(
        self,
        *,
        aihm_version: builtins.str = ...,
        model_id: builtins.str = ...,
        supported_devices: collections.abc.Iterable[builtins.str] | None = ...,
        supported_chipsets: collections.abc.Iterable[builtins.str] | None = ...,
        performance_metrics: collections.abc.Iterable[global___ModelPerf.PerformanceDetails] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["aihm_version", b"aihm_version", "model_id", b"model_id", "performance_metrics", b"performance_metrics", "supported_chipsets", b"supported_chipsets", "supported_devices", b"supported_devices"]) -> None: ...

global___ModelPerf = ModelPerf
