# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
---------------------------------------------------------------------
Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
SPDX-License-Identifier: BSD-3-Clause
---------------------------------------------------------------------
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import shared.precision_pb2
import shared.runtime_pb2
import shared.tool_versions_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ModelReleaseAssets(google.protobuf.message.Message):
    """Schema for model release-assets.yaml files."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class AssetDetails(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PRECISION_FIELD_NUMBER: builtins.int
        RUNTIME_FIELD_NUMBER: builtins.int
        CHIPSET_FIELD_NUMBER: builtins.int
        DOWNLOAD_URL_FIELD_NUMBER: builtins.int
        TOOL_VERSIONS_FIELD_NUMBER: builtins.int
        precision: shared.precision_pb2.Precision.ValueType
        runtime: shared.runtime_pb2.Runtime.ValueType
        chipset: builtins.str
        """Optional for universal assets, set for chipset-specific assets."""
        download_url: builtins.str
        @property
        def tool_versions(self) -> shared.tool_versions_pb2.ToolVersions: ...
        def __init__(
            self,
            *,
            precision: shared.precision_pb2.Precision.ValueType = ...,
            runtime: shared.runtime_pb2.Runtime.ValueType = ...,
            chipset: builtins.str | None = ...,
            download_url: builtins.str = ...,
            tool_versions: shared.tool_versions_pb2.ToolVersions | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["_chipset", b"_chipset", "chipset", b"chipset", "tool_versions", b"tool_versions"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["_chipset", b"_chipset", "chipset", b"chipset", "download_url", b"download_url", "precision", b"precision", "runtime", b"runtime", "tool_versions", b"tool_versions"]) -> None: ...
        def WhichOneof(self, oneof_group: typing.Literal["_chipset", b"_chipset"]) -> typing.Literal["chipset"] | None: ...

    AIHM_VERSION_FIELD_NUMBER: builtins.int
    MODEL_ID_FIELD_NUMBER: builtins.int
    ASSETS_FIELD_NUMBER: builtins.int
    aihm_version: builtins.str
    model_id: builtins.str
    @property
    def assets(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ModelReleaseAssets.AssetDetails]: ...
    def __init__(
        self,
        *,
        aihm_version: builtins.str = ...,
        model_id: builtins.str = ...,
        assets: collections.abc.Iterable[global___ModelReleaseAssets.AssetDetails] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["aihm_version", b"aihm_version", "assets", b"assets", "model_id", b"model_id"]) -> None: ...

global___ModelReleaseAssets = ModelReleaseAssets
