# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: release_assets.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from qai_hub_models_cli.proto.shared import precision_pb2 as shared_dot_precision__pb2
from qai_hub_models_cli.proto.shared import runtime_pb2 as shared_dot_runtime__pb2
from qai_hub_models_cli.proto.shared import tool_versions_pb2 as shared_dot_tool__versions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14release_assets.proto\x12\x05qaihm\x1a\x16shared/precision.proto\x1a\x14shared/runtime.proto\x1a\x1ashared/tool_versions.proto\"\xaf\x02\n\x12ModelReleaseAssets\x12\x14\n\x0c\x61ihm_version\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\x12\x36\n\x06\x61ssets\x18\x03 \x03(\x0b\x32&.qaihm.ModelReleaseAssets.AssetDetails\x1a\xb8\x01\n\x0c\x41ssetDetails\x12#\n\tprecision\x18\x01 \x01(\x0e\x32\x10.qaihm.Precision\x12\x1f\n\x07runtime\x18\x02 \x01(\x0e\x32\x0e.qaihm.Runtime\x12\x14\n\x07\x63hipset\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x0c\x64ownload_url\x18\x04 \x01(\t\x12*\n\rtool_versions\x18\x05 \x01(\x0b\x32\x13.qaihm.ToolVersionsB\n\n\x08_chipsetb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'release_assets_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MODELRELEASEASSETS']._serialized_start=106
  _globals['_MODELRELEASEASSETS']._serialized_end=409
  _globals['_MODELRELEASEASSETS_ASSETDETAILS']._serialized_start=225
  _globals['_MODELRELEASEASSETS_ASSETDETAILS']._serialized_end=409
# @@protoc_insertion_point(module_scope)
