# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------

from __future__ import annotations

import torch
from torch import nn
from typing_extensions import Self

from qai_hub_models.models.simple_bev_cam.external_repos.simple_bev.nets.segnet import (
    Segnet,
)
from qai_hub_models.models.simple_bev_cam.external_repos.simple_bev.utils import vox
from qai_hub_models.utils.asset_loaders import CachedWebModelAsset
from qai_hub_models.utils.base_model import BaseModel
from qai_hub_models.utils.input_spec import (
    InputSpec,
    IoType,
    OutputSpec,
    TensorSpec,
)

MODEL_ID = __name__.split(".")[-2]
MODEL_ASSET_VERSION = 2
DEFAULT_WEIGHTS = "model-000025000.pth"

Z, Y, X = 200, 8, 200
SCENE_CENTROID_X = 0.0
SCENE_CENTROID_Y = 1.0
SCENE_CENTROID_Z = 0.0
XMIN, XMAX = -50, 50
ZMIN, ZMAX = -50, 50
YMIN, YMAX = -5, 5


class SimpleBev(BaseModel):
    def __init__(
        self,
        model: nn.Module,
        use_radar: bool = False,
        use_lidar: bool = False,
        use_metaradar: bool = False,
        do_rgbcompress: bool = True,
        encoder_type: str = "res101",
        device: str = "cpu",
    ) -> None:
        super().__init__()
        self.model = model
        self.scene_centroid_x = SCENE_CENTROID_X
        self.scene_centroid_y = SCENE_CENTROID_Y
        self.scene_centroid_z = SCENE_CENTROID_Z
        self.xmin, self.xmax = XMIN, XMAX
        self.zmin, self.zmax = ZMIN, ZMAX
        self.ymin, self.ymax = YMIN, YMAX
        self.bounds = (self.xmin, self.xmax, self.ymin, self.ymax, self.zmin, self.zmax)
        self.Z, self.Y, self.X = Z, Y, X
        self.scene_centroid = torch.tensor(
            [
                [
                    self.scene_centroid_x,
                    self.scene_centroid_y,
                    self.scene_centroid_z,
                ]
            ],
            dtype=torch.float32,
        )
        self.vox_util_ = vox.Vox_util(
            self.Z,
            self.Y,
            self.X,
            scene_centroid=self.scene_centroid.to("cpu"),
            bounds=self.bounds,
            assert_cube=False,
        )

        self.use_radar = use_radar
        self.use_lidar = use_lidar
        self.use_metaradar = use_metaradar
        self.do_rgbcompress = do_rgbcompress
        self.encoder_type = encoder_type
        self.device = device

    @classmethod
    def from_pretrained(
        cls,
        weights: str = DEFAULT_WEIGHTS,
        use_radar: bool = False,
        use_lidar: bool = False,
        use_metaradar: bool = False,
        do_rgbcompress: bool = True,
        encoder_type: str = "res101",
        device: str = "cpu",
    ) -> Self:
        checkpoint_path = CachedWebModelAsset.from_asset_store(
            MODEL_ID, MODEL_ASSET_VERSION, weights
        ).fetch()
        simple_bev_model = _load_model_from_weight(
            checkpoint_path,
            use_radar,
            use_lidar,
            use_metaradar,
            do_rgbcompress,
            encoder_type,
            device,
        )
        return cls(simple_bev_model)

    def forward(
        self,
        rgb_camXs: torch.Tensor,
        pix_T_cams: torch.Tensor,
        cam0_T_camXs: torch.Tensor,
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor, torch.Tensor]:
        """
        Run Segnet model and return the transformed and segmented object data for generating a 2D bird's eye view(BEV) of the environment around the vehicle

        Parameters
        ----------
        rgb_camXs
            Image data generated by each camera sensor. Shape [B,S,C,H,W] where B = batch size, S = number of cameras, C = 3, H = img height, W = img width
        pix_T_cams
            Camera intrinsic matrix - Used for Projecting 2D image to 3D grid plane. Shape [B,S,4,4]
        cam0_T_camXs
            Transformation matrices from various cameras (camXs) to reference camera (camera0) coordinate. Shape [B,S,4,4]

        Returns
        -------
        raw_e_results: torch.Tensor
            Raw feature data: torch.Tensor of shape (1,k,Z,X).
        feat_e_results: torch.Tensor
            Processed feature data: torch.Tensor of shape (1,k,Z,X).
        seg_e_results: torch.Tensor
            Segmented objects (foreground/background): torch.Tensor of shape (1,1,Z,X).
        center_e_results: torch.Tensor
            Position (1D) of each segmented object. torch.Tensor of shape (1,1,Z,X).
        offset_e_results: torch.Tensor
            Offset position (2D) of each segmented object. torch.Tensor of shape (1,2,Z,X).

            Where k = number of feature points.
        """
        return self.model(rgb_camXs, pix_T_cams, cam0_T_camXs, self.vox_util_)

    def get_input_spec(
        self,
        batch_size: int = 1,
        height: int = 224 * 2,
        width: int = 400 * 2,
    ) -> InputSpec:
        """
        Returns the input specification (name -> (shape, type). This can be
        used to submit profiling job on Qualcomm AI Hub Workbench.
        """
        return {
            "rgb_camXs": TensorSpec(
                shape=(batch_size, 6, 3, height, width),
                dtype="float32",
                io_type=IoType.TENSOR,
            ),
            "pix_T_cams": TensorSpec(
                shape=(batch_size, 6, 4, 4),
                dtype="float32",
                io_type=IoType.TENSOR,
            ),
            "cam0_T_camXs": TensorSpec(
                shape=(batch_size, 6, 4, 4),
                dtype="float32",
                io_type=IoType.TENSOR,
                apply_runtime_channel_reordering=True,
            ),
        }

    def get_output_spec(self) -> OutputSpec:
        return {
            "raw_e_results": TensorSpec(),
            "feat_e_results": TensorSpec(),
            "seg_e_results": TensorSpec(),
            "center_e_results": TensorSpec(),
            "offset_e_results": TensorSpec(
                apply_runtime_channel_reordering=True,
            ),
        }


def _load_model_from_weight(
    checkpoint_path: str,
    use_radar: bool,
    use_lidar: bool,
    use_metaradar: bool,
    do_rgbcompress: bool,
    encoder_type: str,
    device: str,
) -> nn.Module:
    bounds = (XMIN, XMAX, YMIN, YMAX, ZMIN, ZMAX)
    scene_centroid = torch.tensor(
        [[SCENE_CENTROID_X, SCENE_CENTROID_Y, SCENE_CENTROID_Z]],
        dtype=torch.float32,
    )
    scene_centroid = scene_centroid.to("cpu")
    vox_util = vox.Vox_util(Z, Y, X, scene_centroid, bounds, None, assert_cube=False)
    model = Segnet(
        Z,
        Y,
        X,
        vox_util,
        use_radar=use_radar,
        use_lidar=use_lidar,
        use_metaradar=use_metaradar,
        do_rgbcompress=do_rgbcompress,
        encoder_type=encoder_type,
    )
    checkpoint = torch.load(checkpoint_path, weights_only=True, map_location=device)[
        "model_state_dict"
    ]

    model_dict = model.state_dict()

    # 1. filter out ignored keys
    pretrained_dict = dict(checkpoint.items())

    # 2. overwrite entries in the existing state dict
    model_dict.update(pretrained_dict)

    # 3. load the new state dict
    model.load_state_dict(model_dict, strict=False)
    model.to("cpu").eval()
    return model
