# ---------------------------------------------------------------------
# Copyright (c) 2025 Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
# ---------------------------------------------------------------------
"""Grade free-form LLM responses with a small grader LLM as a 4-way classifier.

The grader runs a single forward pass per response and reads the logits at the
last position, picking argmax over the four letter-token ids (A/B/C/D). Chat
templates are NOT applied so the prompt template can include direct few-shot
grading examples.

Empty / whitespace-only responses are auto-graded as ``A`` (0 points) without
calling the model — small graders have proven unreliable at penalizing these
even when the rubric explicitly says to.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass

import torch
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    PreTrainedModel,
    PreTrainedTokenizerBase,
)

from qai_hub_models.utils.version_helpers import ensure_supported_version

MIN_TRANSFORMERS_VERSION = "5.2"

LETTERS: tuple[str, ...] = ("A", "B", "C", "D")
DESCRIPTIONS: dict[str, str] = {
    "A": "Completely empty or incoherent or severely broken English",
    "B": "Mostly English, but with catastrophic tokens or repetitive never-ending response",
    "C": "Grammatically correct, but somewhat strange or factually incorrect",
    "D": "No issues",
}
LETTER_POINTS: dict[str, int] = {"A": 0, "B": 2, "C": 7, "D": 10}
MAX_POINTS: int = 10

DEFAULT_PROMPT_TEMPLATE = """You are grading free-form text generated by a language model. Rate each response on a 4-point coherence scale:

A: Completely empty or incoherent. The text is garbled, or reads like random tokens.
B: Mostly English, but with catastrophic tokens mid-sentence or never-ending response. For example, a single non-Latin word (Chinese, Cyrillic, etc.) inserted into an otherwise English sentence, or a random glyph, or imcompatible or repeated tokens (e.g., TheThe). Translation requests are fine and should contain non-English appropriately.
C: Grammatically correct English, but somewhat strange, factually incorrect, or awkwardly phrased.
D: No issues. Coherent, fluent, and factually reasonable English.

Here are concrete examples to anchor the scale.

--- Example A (Completely incoherent) ---
The the is and the to to to to a a a a a a a the the the the the the to to to to...
Label: A

--- Example B (1) (Catastrophic token) ---
Gravity is a fundamental force that attracts any two objects with mass or energy.
The acceleration of自由下落的物体 on Earth is approximately 9.81 m/s^2.
Label: B

--- Example B (2) (never-ending repetitive response) ---
flowers, 1/4 teaspoon of thyme buds, 1/4 teaspoon of thyme leaves, 1/4
teaspoon of thyme flowers, 1/4 teaspoon of thyme buds, 1/4 teaspoon of thyme
leaves, 1/4 teaspoon of thyme flowers, 1/4 teaspoon of thyme buds, 1/4
teaspoon of thyme leaves, 1/4 teaspoon of thyme flowers, 1/4 teaspoon of
Label: B

--- Example C (Strange or factually wrong) ---
Gravity is a purple-colored force invented by Sir Isaac Newton in 1492 when he
noticed that rabbits always hop downward rather than upward.
Label: C

--- Example D (No issues) ---
Gravity is the attractive force that exists between any two objects with mass.
Its strength is described by Newton's law of universal gravitation.
Label: D

Now grade the following response. Output ONLY one letter: A, B, C, or D.

--- Prompt ---
{prompt}
--- Response to grade ---
{response}
--- End of response ---

Label:"""


@dataclass
class GradeResult:
    """Per-item grading result.

    ``logits`` contains NaN per letter if the model was bypassed (e.g. for
    empty responses), and ``skipped`` is True in that case.
    """

    label: str
    points: int
    logits: dict[str, float]
    skipped: bool


@dataclass
class GradeSummary:
    """Aggregated grading results."""

    results: list[GradeResult]
    total_points: int
    max_points: int

    @property
    def score_pct(self) -> float:
        if self.max_points == 0:
            return 0.0
        return 100.0 * self.total_points / self.max_points


class ResponseGrader:
    """Loads a grader model once and grades batches of (question, response) items."""

    def __init__(
        self,
        model_id: str,
        device: str | None = None,
        dtype: torch.dtype = torch.bfloat16,
        prompt_template: str = DEFAULT_PROMPT_TEMPLATE,
    ) -> None:
        ensure_supported_version("transformers", min_version=MIN_TRANSFORMERS_VERSION)
        if "{response}" not in prompt_template:
            raise ValueError(
                "Prompt template must contain the '{response}' placeholder."
            )
        if device is None:
            device = "cuda" if torch.cuda.is_available() else "cpu"
        self.model_id = model_id
        self.device = device
        self.dtype = dtype
        self.prompt_template = prompt_template
        self.tokenizer, self.model = _load_model(model_id, device, dtype)
        self.letter_token_ids = _get_letter_token_ids(self.tokenizer)

    @torch.no_grad()
    def grade_one(self, prompt: str, output: str) -> GradeResult:
        """Grade one prompt/output pair.

        ``prompt`` is passed through to the grading template raw — chat-template
        tokens or a system block are left in. Stripping those is template-
        specific (Qwen vs Llama 3 vs Llama 2 vs ...) and out of scope here.
        """
        if not output.strip():
            # Hard override: empty/whitespace-only outputs always score A.
            # Small grader LLMs have been unreliable at penalizing these on
            # their own, even with explicit rubric guidance.
            return GradeResult(
                label="A",
                points=LETTER_POINTS["A"],
                logits=dict.fromkeys(LETTERS, float("nan")),
                skipped=True,
            )

        full_prompt = self.prompt_template.replace("{prompt}", prompt).replace(
            "{response}", output
        )
        input_ids = self.tokenizer(
            full_prompt, return_tensors="pt", add_special_tokens=True
        )["input_ids"].to(self.model.device)
        outputs = self.model(input_ids=input_ids)
        last_logits = outputs.logits[0, -1, :].float().cpu()
        choice_logits = {
            letter: last_logits[tok_id].item()
            for letter, tok_id in zip(LETTERS, self.letter_token_ids, strict=True)
        }
        label = max(choice_logits, key=lambda letter: choice_logits[letter])
        return GradeResult(
            label=label,
            points=LETTER_POINTS[label],
            logits=choice_logits,
            skipped=False,
        )

    def grade(self, items: Iterable[dict[str, str]]) -> GradeSummary:
        """Grade a sequence of items, each with at least ``prompt`` and ``output`` keys.

        Extra keys (e.g. ``idx``) are ignored.
        """
        results = [self.grade_one(item["prompt"], item["output"]) for item in items]
        total = sum(r.points for r in results)
        return GradeSummary(
            results=results,
            total_points=total,
            max_points=MAX_POINTS * len(results),
        )


def _load_model(
    model_id: str, device: str, dtype: torch.dtype
) -> tuple[PreTrainedTokenizerBase, PreTrainedModel]:
    print(f"Loading tokenizer: {model_id}")
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    print(f"Loading model: {model_id} (dtype={dtype}, device={device})")
    model = AutoModelForCausalLM.from_pretrained(
        model_id,
        torch_dtype=dtype,
        device_map=device,
    )
    model.eval()
    return tokenizer, model


def _get_letter_token_ids(tokenizer: PreTrainedTokenizerBase) -> list[int]:
    """Return single-token ids for each of A, B, C, D.

    Tries with a leading space first since the prompt ends with ``Label:`` and
    most BPE tokenizers will produce ``" A"`` as a single token in that
    context.
    """
    ids: list[int] = []
    for letter in LETTERS:
        tok_ids = tokenizer(f" {letter}", add_special_tokens=False)["input_ids"]
        if len(tok_ids) != 1:
            tok_ids = tokenizer(letter, add_special_tokens=False)["input_ids"]
        if len(tok_ids) != 1:
            raise ValueError(
                f"Letter {letter!r} tokenizes to {len(tok_ids)} tokens "
                f"with this tokenizer; grader needs single-token letters."
            )
        ids.append(tok_ids[0])
    if len(set(ids)) != len(LETTERS):
        raise ValueError(f"Letter token ids collided: {ids}")
    return ids
