##
## QAI Hub Models GPU Nightly Tests
##

name: GPU Nightly
run-name: "GPU Nightly (${{ inputs.deployment || 'prod' }}, ${{ inputs.models || 'all' }})"

on:
  # Allows this workflow to be manually triggered.
  workflow_dispatch:
    inputs:
      models:
        description: Models to Run
        required: false
        type: string
        default: all

      deployment:
        description: Hub Deployment
        default: prod
        type: string

  schedule:
    - cron: '0 2 * * 0,1,2,4,5,6' # Nightly: Every day except Tuesday 6pm PST (7pm PDT, Wednesday 2am UTC)


jobs:
  nightly:
    uses: ./.github/workflows/gpu_weekly.yml
    with:
      models: ${{ inputs.models || 'all' }}
      deployment: ${{ inputs.deployment || 'prod' }}
      test_suite: nightly
    secrets: inherit
