name: Test Models

on:
  workflow_call:
    inputs:
      deployment:
        default: prod
        type: string

      test_devices:
        default: all
        type: string

      test_runtimes:
        default: default
        type: string

      test_precisions:
        default: default
        type: string

      qairt_version:
        type: string
        default: qaihm_default

      models:
        type: string
        default: all

      test_scope:
        # Options: unit, unit_and_compile, compile_only, perf, accuracy, perf_and_accuracy
        description: Test Scope
        type: string
        default: perf

      ignore_job_cache:
        default: true
        type: boolean

      ignore_known_failures:
        description: Ignore known failures (do not fail tests for models with known issues)
        default: true
        type: boolean

      split_name:
        description: Scorecard may be split into sub-actions, so multiple models can run in parallel. This is the name of the split.
        required: false
        type: string
        default: ''

      sync_assets_branch:
        description: Branch containing synced static asset configs
        type: string
        default: ''

      python_version:
        description: Python version for artifact naming
        type: string
        default: '3.10'

env:
  # Versions MUST be quoted, otherwise they will be interpreted as a floats
  # (and version like 3.10 can be interpreted as 3.1).
  PYTHON_VERSION: ${{ inputs.python_version }}
  PYTHONUNBUFFERED: 1
  QAIHM_CI: 1
  VENV_PATH: build/ci-envs/qaihm-build
  CMAKE_ARGS: -DCMAKE_POLICY_VERSION_MINIMUM=3.5

jobs:
  exec_scorecard:
    runs-on: [tetra-ubuntu-2204, self-hosted]
    timeout-minutes: 600 # 10 hours - just for job submission
    env:
      QAIHM_TEST_IGNORE_KNOWN_FAILURES: ${{ inputs.ignore_known_failures && '1' || '0' }}
      QAIHM_TEST_DEPLOYMENT: ${{ inputs.deployment }}
      QAIHM_TEST_ARTIFACTS_DIR: build/scorecard-yamls/${{ github.run_id }}
      QAIHM_TEST_DEVICES: ${{ inputs.test_devices }}
      QAIHM_TEST_PATHS: ${{ inputs.test_runtimes }}
      QAIHM_TEST_MODELS: ${{ inputs.models }}
      QAIHM_TEST_PRECISIONS: ${{ inputs.test_precisions }}
      QAIHM_TEST_QAIRT_VERSION: ${{ inputs.qairt_version }}
      QAIHM_TEST_IGNORE_DEVICE_JOB_CACHE: ${{ inputs.ignore_job_cache }}
      HUGGING_FACE_HUB_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }} # used for llama tests
      COMPILE_JOBS_URL: NONE

    name: Submit Scorecard Jobs${{ inputs.split_name != '' && format(' ({0})', inputs.split_name) || '' }}
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v6

      - id: install_platform_deps
        env:
          SUDO_PASSWORD: "${{ secrets.TETRASERVICE_PASSWORD }}"
        run: |
          bash scripts/ci/install-platform-deps.sh

      - id: setup_python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Check Out Updated Static Asset Configs
        if: ${{ inputs.sync_assets_branch != '' }}
        run: |
          git fetch origin ${{ inputs.sync_assets_branch }}
          git checkout origin/${{ inputs.sync_assets_branch }} -- qai_hub_models/scorecard/static/models

      - name: Create Virtual Env
        run: |
          python3 scripts/build_and_test.py \
            --venv="${{ env.VENV_PATH }}" \
            --python="${{ steps.setup_python.outputs.python-path }}" \
            install_deps

      - name: Setup AWS Credentials
        uses: ./.github/actions/configure-multiple-aws-roles
        with:
          role-to-assume: ${{ secrets.QAIHM_CI_AWS_ROLE_ARN }}
          role-duration-seconds: 43200 # 12 hours
          profile: qaihm
          aws-region: us-west-2

      - name: Configure Hub Credentials
        run: |
          # Add envvars for "public" client (jobs accessible to anyone in the company)
          source scripts/ci/set-aihub-credential-vars.sh \
            ${{ env.QAIHM_TEST_DEPLOYMENT }},prod \
            ${{ secrets['HUB_USER_TOKEN_PROD'] }} \
            ${{ secrets['HUB_USER_TOKEN_STAGING'] }} \
            ${{ secrets['HUB_USER_TOKEN_DEV'] }} \
            ${{ secrets['HUB_USER_TOKEN_SANDBOX'] }} \
            DEFAULT \
            ${{ env.VENV_PATH }}

          # Add envvars for "private" client (jobs accessible to AI Hub team)
          source scripts/ci/set-aihub-credential-vars.sh \
            ${{ env.QAIHM_TEST_DEPLOYMENT }},prod \
            ${{ secrets['HUB_PRIVATE_USER_TOKEN_PROD'] }} \
            ${{ secrets['HUB_PRIVATE_USER_TOKEN_STAGING'] }} \
            ${{ secrets['HUB_PRIVATE_USER_TOKEN_DEV'] }} \
            ${{ secrets['HUB_USER_TOKEN_SANDBOX'] }} \
            PRIVATE

      - name: Dump Environment Variables to File
        id: dump_env
        run: |
          source "${{env.VENV_PATH}}/bin/activate"
          # Dumping Envrionment Variables Needed by Scorecard Collection Job
          ENVIRONMENT_FILE=${{ env.QAIHM_TEST_ARTIFACTS_DIR }}/environment.env
          mkdir -p "${{ env.QAIHM_TEST_ARTIFACTS_DIR }}"
          echo "QAIHM_TEST_DEPLOYMENT=${{ env.QAIHM_TEST_DEPLOYMENT }}" >> $ENVIRONMENT_FILE
          echo "QAIHM_TEST_MODELS=${{ env.QAIHM_TEST_MODELS }}" >> $ENVIRONMENT_FILE
          echo "QAIHM_TEST_DEVICES=${{ env.QAIHM_TEST_DEVICES }}" >> $ENVIRONMENT_FILE
          echo "QAIHM_TEST_PATHS=${{ env.QAIHM_TEST_PATHS }}" >> $ENVIRONMENT_FILE
          echo "QAIHM_TEST_PRECISIONS=${{ env.QAIHM_TEST_PRECISIONS }}" >> $ENVIRONMENT_FILE
          echo "QAIHM_TEST_QAIRT_VERSION=${{ env.QAIHM_TEST_QAIRT_VERSION }}" >> $ENVIRONMENT_FILE
          echo "QAIHM_TEST_IGNORE_KNOWN_FAILURES=${{ env.QAIHM_TEST_IGNORE_KNOWN_FAILURES }}" >> $ENVIRONMENT_FILE
          echo "QAIHM_TEST_IGNORE_DEVICE_JOB_CACHE=${{ inputs.ignore_job_cache }}" >> $ENVIRONMENT_FILE
          echo "QAIHM_TEST_SCOPE=${{ inputs.test_scope }}" >> $ENVIRONMENT_FILE

      - name: Create Test Results Directory
        run: |
          mkdir -p ${{ github.workspace }}/build/test-results

      - name: Set JUnit XML Environment Variables
        run: |
          echo "QAIHM_JUNIT_XML_PATH=${{ github.workspace }}/build/test-results/qaihm-junit.xml" >> "$GITHUB_ENV"

      - name: Verify Job Count
        if: ${{ inputs.test_scope != 'compile_only' && inputs.test_scope != 'unit' && inputs.test_scope != 'unit_and_compile' }}
        run: |
          source "${{env.VENV_PATH}}/bin/activate"
          if [[ "${{ github.event_name }}" != "schedule" ]]; then
            python qai_hub_models/scripts/count_device_jobs.py --assert-valid-daytime-scorecard
          else
            python qai_hub_models/scripts/count_device_jobs.py
          fi

      - name: Dump QAIRT Versions to Disk
        id: dump_qairt
        run: |
          source "${{env.VENV_PATH}}/bin/activate"
          python qai_hub_models/scripts/dump_scorecard_tool_versions.py

      - name: Run Unit Tests (Pytorch Recipes)
        id: run-unit-tests
        if: ${{ !cancelled() && inputs.test_scope == 'unit' }}
        env:
          QAIHM_JUNIT_XML_PATH: ${{ github.workspace }}/build/test-results/models-junit.xml
        run: |
          python3 scripts/build_and_test.py \
            --venv="${{ env.VENV_PATH }}" \
            --python="${{ steps.setup_python.outputs.python-path }}" \
            test_unit_all_models

      - name: Run Compile Jobs (Static Models)
        id: run-compile-jobs-static
        if: ${{ !cancelled() && inputs.test_scope != 'unit' && inputs.test_scope != 'unit_and_compile' }}
        run: |
          source "${{env.VENV_PATH}}/bin/activate"
          python qai_hub_models/scorecard/static/scripts/exec_models.py --skip-profile --skip-inference

      - name: Run Pre-Quantize ONNX Compile Jobs (Pytorch Recipes)
        id: run-pre-quantize-compile-jobs
        if: ${{ !cancelled() && env.QAIHM_TEST_PRECISIONS != 'float' && inputs.test_scope != 'unit' }}
        env:
          QAIHM_JUNIT_XML_PATH: ${{ github.workspace }}/build/test-results/pre-quantize-compile-junit.xml
        run: |
          python3 scripts/build_and_test.py \
            --venv="${{ env.VENV_PATH }}" \
            --python="${{ steps.setup_python.outputs.python-path }}" \
            test_pre_quantize_compile_all_models

      - name: Run Quantize Jobs (Pytorch Recipes)
        id: run-quantize-jobs
        if: ${{ !cancelled() && env.COMPILE_JOBS_URL == 'NONE' && env.QAIHM_TEST_PRECISIONS != 'float' && inputs.test_scope != 'unit' }}
        env:
          QAIHM_JUNIT_XML_PATH: ${{ github.workspace }}/build/test-results/quantize-junit.xml
        run: |
          python3 scripts/build_and_test.py \
            --venv="${{ env.VENV_PATH }}" \
            --python="${{ steps.setup_python.outputs.python-path }}" \
            test_quantize_all_models

      - name: Run Compile Jobs (Pytorch Recipes)
        id: run-compile-jobs
        if: ${{ !cancelled() && env.COMPILE_JOBS_URL == 'NONE' && inputs.test_scope != 'unit' }}
        env:
          QAIHM_JUNIT_XML_PATH: ${{ github.workspace }}/build/test-results/compile-junit.xml
        run: |
          if [[ "${{ inputs.test_scope }}" == "unit_and_compile" ]]; then
            COMPILE_TASK="test_unit_and_compile_all_models"
          else
            COMPILE_TASK="test_compile_all_models"
          fi
          python3 scripts/build_and_test.py \
            --venv="${{ env.VENV_PATH }}" \
            --python="${{ steps.setup_python.outputs.python-path }}" \
            "$COMPILE_TASK"

      - name: Run Profile & Inference Jobs (Static Models)
        id: run-profile-jobs-static
        if: ${{ !cancelled() && inputs.test_scope != 'unit' && inputs.test_scope != 'unit_and_compile' && inputs.test_scope != 'compile_only' && steps.run-compile-jobs-static.conclusion == 'success' }}
        run: |
          source "${{env.VENV_PATH}}/bin/activate"
          if [[ "${{ inputs.test_scope }}" == "perf" ]]; then
            python qai_hub_models/scorecard/static/scripts/exec_models.py --skip-compile --skip-inference
          elif [[ "${{ inputs.test_scope }}" == "accuracy" ]]; then
            python qai_hub_models/scorecard/static/scripts/exec_models.py --skip-compile --skip-profile
          elif [[ "${{ inputs.test_scope }}" == "perf_and_accuracy" ]]; then
            python qai_hub_models/scorecard/static/scripts/exec_models.py --skip-compile
          fi

      - name: Run Profile & Inference Jobs (Pytorch Recipes)
        id: run-profile-jobs-e2e
        if: ${{ !cancelled() && inputs.test_scope != 'unit' && inputs.test_scope != 'unit_and_compile' && inputs.test_scope != 'compile_only' && steps.run-compile-jobs.conclusion == 'success' }}
        env:
          QAIHM_JUNIT_XML_PATH: ${{ github.workspace }}/build/test-results/profile-inference-junit.xml
        run: |
          source "${{env.VENV_PATH}}/bin/activate"
          if [[ "${{ inputs.test_scope }}" == "perf" ]]; then
            QAIHM_TEST_DEVICE_TASK="test_profile_all_models"
          elif [[ "${{ inputs.test_scope }}" == "accuracy" ]]; then
            QAIHM_TEST_DEVICE_TASK="test_inference_all_models"
          elif [[ "${{ inputs.test_scope }}" == "perf_and_accuracy" ]]; then
            QAIHM_TEST_DEVICE_TASK="test_profile_inference_all_models"
          fi
          python3 scripts/build_and_test.py \
            --venv="${{ env.VENV_PATH }}" \
            --python="${{ steps.setup_python.outputs.python-path }}" \
            "$QAIHM_TEST_DEVICE_TASK"

      - name: Combine JUnit XML Files
        if: ${{ always() }}
        run: |
          source "${{ env.VENV_PATH }}/bin/activate"
          python scripts/combine_junit_xml.py \
            --junit-xml build/test-results \
            --output build/combined-test-results/qaihm-model-tests${{ inputs.split_name != '' && format('-{0}', inputs.split_name) || '' }}-junit.xml

      - name: Upload Test Results
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: test-results-${{ (inputs.test_scope == 'unit' || inputs.test_scope == 'unit_and_compile') && 'models' || 'scorecard-models' }}-py${{ inputs.python_version }}${{ inputs.split_name != '' && format('-{0}', inputs.split_name) || '' }}
          path: build/combined-test-results

      - name: Clean Up Artifacts
        if: ${{ always() && steps.dump_env.outcome == 'success' }}
        id: intermediate-cleanup
        # These folders contain the actual datasets used in evaluation
        # so we don't want to upload them since they are multiple GBs.
        run: |
          rm -rf ${{ env.QAIHM_TEST_ARTIFACTS_DIR }}/hub_datasets
          rm -rf ${{ env.QAIHM_TEST_ARTIFACTS_DIR }}/hub_datasets_nt

      - name: Upload Scorecard Cached Artifacts
        # Always run this step, even if the job is cancelled.
        # That way we can kill scorecards early and still get access to intermediate artifacts.
        if: ${{ always() && steps.dump_env.outcome == 'success' && inputs.test_scope != 'unit' }}
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.test_scope == 'unit_and_compile' && 'Test' || 'Scorecard' }} Cached Artifact (Flaky-Job-IDs, ${{ github.run_id }}, py${{ inputs.python_version }}${{ inputs.split_name != '' && format(', {0}', inputs.split_name) || '' }})
          path: ${{ env.QAIHM_TEST_ARTIFACTS_DIR }}
